import { useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { useNavigate, useParams } from "react-router-dom";
import { AlertTriangle, ArrowLeft, Bell, CheckCircle2, Clock3, Copy, Loader2, MessageCircle, Pencil, RefreshCw, RotateCcw, Send, Trash2, XCircle } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { formatBRL } from "@/lib/split/math";

const labels:Record<string,string>={active:"Aguardando pagamentos",settled:"Tudo recebido",cancelled:"Cancelada",pending:"Pendente",partial:"Recebido em parte",paid:"Pago",notified:"Avisado"};
const messageLabels:Record<string,string>={queued:"Preparando o envio",processing:"Preparando o envio",enqueued:"Na fila do WhatsApp",sent:"Enviada ao WhatsApp",delivered:"Entregue",read:"Lida",failed:"Falha no envio",dead:"Não entregue",skipped:"Não enviada"};
const terminalMessageStatuses=new Set(["sent","delivered","read","failed","dead","skipped"]);

export default function DivisaoDoRoleDetalhe() {
  const { id }=useParams(); const nav=useNavigate();
  const queryClient = useQueryClient();
  const [split,setSplit]=useState<any>(null); const [parts,setParts]=useState<any[]>([]); const [events,setEvents]=useState<any[]>([]);
  const [messages,setMessages]=useState<Record<string,any>>({}); const [busy,setBusy]=useState(false);
  const load=async()=>{
    const [{data:s,error},{data:p},{data:e},{data:m}]=await Promise.all([
      supabase.from("shared_expenses" as never).select("*").eq("id" as never,id as never).single(),
      supabase.from("shared_expense_participants" as never).select("*").eq("shared_expense_id" as never,id as never).order("created_at" as never),
      supabase.from("shared_expense_events" as never).select("*").eq("shared_expense_id" as never,id as never).order("created_at" as never,{ascending:false}).limit(30),
      supabase.rpc("split_message_status" as never,{p_id:id} as never),
    ]);
    if(error){toast.error("Divisão não encontrada");nav("/app/divisao-do-role");return;}
    setSplit(s);setParts((p??[]) as any[]);setEvents((e??[]) as any[]);
    setMessages(Object.fromEntries(((m??[]) as any[]).map((x)=>[x.participant_id,x])));
  };
  useEffect(()=>{load();const timer=window.setInterval(load,6000);return()=>window.clearInterval(timer);},[id]);
  const external=useMemo(()=>parts.filter((p)=>p.phone_e164),[parts]);
  const received=external.reduce((s,p)=>s+Number(p.amount_paid),0), pending=external.reduce((s,p)=>s+Math.max(0,Number(p.amount_due)-Number(p.amount_paid)),0);
  const externalTotal=received+pending,progress=externalTotal?Math.min(100,Math.round(received/externalTotal*100)):100;
  const overdue=split?.due_date&&split.status==="active"&&split.due_date<new Date().toISOString().slice(0,10);
  const refreshFinance=()=>{queryClient.invalidateQueries({queryKey:["shared_expenses"]});queryClient.invalidateQueries({queryKey:["transactions"]});queryClient.invalidateQueries({queryKey:["accounts"]});queryClient.invalidateQueries({queryKey:["credit_cards"]});queryClient.invalidateQueries({queryKey:["dashboard"]});};
  const act=async(fn:()=>PromiseLike<{error?:any}>,ok:string)=>{setBusy(true);try{const r=await fn();if(r.error)throw r.error;refreshFinance();toast.success(ok);await load();}catch(e:any){toast.error(friendlyError(e));}finally{setBusy(false)}};
  const payment=(pid:string,amount:number)=>act(()=>supabase.rpc("split_add_payment_v2" as never,{p_participant_id:pid,p_amount:amount} as never),"Pagamento registrado");
  const retry=(pid:string,kind:string)=>act(()=>supabase.rpc("split_enqueue_message" as never,{p_expense_id:id,p_participant_id:pid,p_kind:kind||"reminder",p_when:new Date().toISOString()} as never),"Nova tentativa preparada");
  const kick=async()=>{setBusy(true);try{const{error}=await supabase.functions.invoke("split-reminders-dispatch",{body:{owner_only:true}});if(error)throw error;toast.success("Envio retomado");await load();}catch{toast.error("Não consegui retomar agora. Tente novamente em instantes.");}finally{setBusy(false)}};
  const cancel=async()=>{const reason=prompt("Motivo do cancelamento (opcional):")??"";if(!confirm("Cancelar as cobranças e preservar este rolê no histórico? O lançamento financeiro será mantido."))return;await act(()=>supabase.rpc("split_cancel" as never,{p_id:id,p_reason:reason||null,p_remove_transaction:false} as never),"Divisão cancelada");};
  const remove=async()=>{if(!confirm("Excluir este rolê? O gasto sairá das movimentações e este registro ficará apenas no histórico de excluídos."))return;await act(()=>supabase.rpc("split_delete" as never,{p_id:id} as never),"Rolê excluído");};
  const sendAll=()=>act(()=>supabase.rpc("split_send_reminders" as never,{p_shared_expense_id:id} as never),"Lembretes preparados");
  const participantMessages=external.map((p)=>messages[p.id]).filter(Boolean);
  const pendingInvite=participantMessages.some((m)=>m.kind==="invite"&&!terminalMessageStatuses.has(m.outbound_status??m.job_status));
  const deliveredCount=participantMessages.filter((m)=>["sent","delivered","read"].includes(m.outbound_status)).length;
  const failedCount=participantMessages.filter((m)=>["failed","dead"].includes(m.outbound_status??m.job_status)).length;
  const overallStatus=failedCount?`${failedCount} envio${failedCount===1?" precisa":"s precisam"} de atenção`:pendingInvite?"Estamos enviando os convites":deliveredCount===external.length&&external.length?"Convites enviados":"Acompanhamento do rolê";
  if(!split)return <div className="grid place-items-center py-12"><Loader2 className="animate-spin"/></div>;
  return <div className="space-y-5 pb-8 pt-2">
    <button onClick={()=>nav(-1)} className="inline-flex items-center gap-1 text-xs text-muted-foreground"><ArrowLeft size={14}/> Voltar</button>
    <header className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h1 className="font-display text-2xl font-bold">{split.title}</h1>{split.deleted_at&&<span className="rounded-full bg-secondary px-2 py-1 text-[10px] font-semibold text-muted-foreground">Excluída</span>}</div><p className="text-xs text-muted-foreground">{new Date(`${split.occurred_at}T12:00:00`).toLocaleDateString("pt-BR")} · <span className={overdue?"font-semibold text-destructive":""}>{split.deleted_at?"Somente no histórico":overdue?"Vencida":labels[split.status]??split.status}</span></p></div>{split.status!=="cancelled"&&<button onClick={()=>nav(`/app/divisao-do-role/${id}/editar`)} className="rounded-full border p-2" aria-label="Editar"><Pencil size={16}/></button>}</header>
    {!split.deleted_at&&external.length>0&&<section className="surface-card overflow-hidden"><div className="flex items-start gap-3 border-b border-border p-4"><div className={`grid h-10 w-10 shrink-0 place-items-center rounded-full ${failedCount?"bg-destructive/10 text-destructive":pendingInvite?"bg-primary/10 text-primary":"bg-success/10 text-success"}`}>{failedCount?<AlertTriangle size={18}/>:pendingInvite?<Loader2 size={18} className="animate-spin"/>:<MessageCircle size={18}/>}</div><div><p className="text-sm font-semibold">{overallStatus}</p><p className="mt-0.5 text-xs text-muted-foreground">{pendingInvite?"Isso normalmente leva menos de um minuto. Você pode sair desta tela — continuaremos por aqui.":failedCount?"Veja abaixo quem precisa de uma nova tentativa.":"Você acompanha cada convite e pagamento nesta tela."}</p></div></div><div className="grid grid-cols-3 gap-1 p-3 text-center"><JourneyStep icon={<Clock3 size={14}/>} label="Preparado" active/><JourneyStep icon={<Send size={14}/>} label="Enviado" active={deliveredCount>0}/><JourneyStep icon={<CheckCircle2 size={14}/>} label="Recebido" active={received>0}/></div></section>}
    {split.deleted_at&&<div className="rounded-2xl border border-border bg-secondary/50 p-4 text-xs text-muted-foreground"><p className="font-semibold text-foreground">Este rolê foi excluído</p><p className="mt-1">O gasto foi removido das movimentações. Mantivemos este registro somente no histórico para não perder a rastreabilidade.</p></div>}
    <section className="surface-card p-4"><div className="grid grid-cols-3 gap-3"><Metric label="Total" value={formatBRL(Number(split.total_amount))}/><Metric label="Recebido" value={formatBRL(received)} tone="text-success"/><Metric label="Falta" value={formatBRL(pending)} tone={pending?"text-destructive":"text-success"}/></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-gradient-to-r from-primary to-brand-coral transition-all" style={{width:`${progress}%`}}/></div><p className="mt-1 text-right text-[11px] text-muted-foreground">{progress}% recebido</p></section>
    {overdue&&<div className="flex gap-2 rounded-2xl border border-destructive/20 bg-destructive/5 p-3 text-xs text-destructive"><AlertTriangle size={16}/> Há pessoas com pagamento atrasado.</div>}
    {split.status==="active"&&<button disabled={busy||pendingInvite} onClick={sendAll} className="btn-primary w-full disabled:opacity-50"><Bell size={14}/> {pendingInvite?"Enviando convite inicial…":"Lembrar quem ainda não pagou"}</button>}
    <section className="surface-card divide-y divide-border overflow-hidden">{parts.map((p)=>{const left=Math.max(0,Number(p.amount_due)-Number(p.amount_paid));const msg=messages[p.id];const isOwner=!p.phone_e164;const messageStatus=msg?.outbound_status??msg?.job_status;const stalled=msg&&!["sent","delivered","read","failed","dead","skipped"].includes(messageStatus)&&Date.now()-new Date(msg.updated_at).getTime()>120000;const canRetry=["failed","dead","skipped"].includes(messageStatus);return <article key={p.id} className="space-y-2 p-4"><div className="flex justify-between gap-2"><div><p className="text-sm font-semibold">{isOwner?`${p.name} (você)`:p.name}</p><p className="text-[11px] text-muted-foreground">{isOwner?"Sua parte":p.phone_masked??"Sem WhatsApp"} · {formatBRL(Number(p.amount_paid))} de {formatBRL(Number(p.amount_due))}</p></div><span className={`h-fit rounded-full px-2 py-1 text-[10px] ${p.status==="paid"?"bg-success/15 text-success":"bg-secondary text-muted-foreground"}`}>{labels[p.status]??p.status}</span></div>{!isOwner&&msg&&<div className={`rounded-xl px-3 py-2 text-[11px] ${canRetry||stalled?"bg-destructive/5 text-destructive":"bg-secondary/60"}`}><div className="flex items-center justify-between gap-2"><span className="font-medium">{stalled?"O envio está demorando":messageLabels[messageStatus]??messageStatus}</span><span className="text-[10px] opacity-70">{new Date(msg.updated_at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</span></div>{(canRetry||stalled)&&<p className="mt-1">{stalled?"Você pode retomar o processamento sem criar outra cobrança.":"Não conseguimos concluir. Você pode tentar novamente."}</p>}</div>}{left>0&&split.status==="active"&&<div className="flex flex-wrap gap-2"><button disabled={busy} onClick={()=>payment(p.id,left)} className="rounded-full bg-success/15 px-3 py-1 text-xs text-success"><CheckCircle2 size={12} className="inline"/> Marcar {formatBRL(left)}</button><button disabled={busy} onClick={()=>{const v=prompt("Quanto foi recebido?");const n=Number((v??"").replace(",","."));if(n>0)payment(p.id,n)}} className="rounded-full border px-3 py-1 text-xs">Valor parcial</button>{!isOwner&&stalled&&<button disabled={busy} onClick={kick} className="rounded-full border px-3 py-1 text-xs"><RefreshCw size={12} className="inline"/> Retomar envio</button>}{!isOwner&&canRetry&&<button disabled={busy} onClick={()=>retry(p.id,msg?.kind??"reminder")} className="rounded-full border px-3 py-1 text-xs"><RefreshCw size={12} className="inline"/> Tentar novamente</button>}</div>}{Number(p.amount_paid)>0&&!isOwner&&<button disabled={busy} onClick={()=>act(()=>supabase.rpc("split_reverse_payment_v2" as never,{p_participant_id:p.id} as never),"Pagamento desfeito")} className="text-xs text-muted-foreground"><RotateCcw size={11} className="inline"/> Desfazer</button>}</article>})}</section>
    {!split.deleted_at&&<div className="grid grid-cols-2 gap-2"><button onClick={()=>navigator.clipboard.writeText(`${split.title} · ${formatBRL(pending)} pendente${split.pix_key?` · Pix ${split.pix_key}`:""}`).then(()=>toast.success("Dados copiados"))} className="btn-ghost-brand"><Copy size={14}/> Copiar dados</button>{split.status!=="cancelled"&&<button onClick={cancel} className="inline-flex items-center justify-center gap-2 rounded-full border border-destructive/30 px-4 py-2 text-sm text-destructive"><XCircle size={14}/> Cancelar</button>}{split.status!=="cancelled"&&received===0&&<button onClick={remove} className="col-span-2 inline-flex items-center justify-center gap-2 rounded-full px-4 py-2 text-xs text-muted-foreground"><Trash2 size={13}/> Excluir rolê e lançamento</button>}</div>}
    {events.length>0&&<details className="surface-card p-4"><summary className="cursor-pointer text-xs font-semibold">Histórico da divisão</summary><ul className="mt-3 space-y-2 text-[11px] text-muted-foreground">{events.map((e)=><li key={e.id}>{new Date(e.created_at).toLocaleString("pt-BR")} · {eventLabel(e.event_type)}</li>)}</ul></details>}
  </div>;
}
function Metric({label,value,tone=""}:{label:string;value:string;tone?:string}){return <div><p className="text-[10px] text-muted-foreground">{label}</p><p className={`text-sm font-bold ${tone}`}>{value}</p></div>}
function JourneyStep({icon,label,active}:{icon:ReactNode;label:string;active:boolean}){return <div className={`flex flex-col items-center gap-1 rounded-xl px-2 py-2 text-[10px] ${active?"bg-primary/10 font-semibold text-primary":"text-muted-foreground"}`}><span>{icon}</span><span>{label}</span></div>}
function eventLabel(v:string){return ({created:"Divisão criada",updated:"Divisão editada",payment:"Pagamento registrado",reverse_payment:"Pagamento desfeito",message_queued:"Mensagem preparada",message_enqueued:"Mensagem entrou na fila do WhatsApp",cancelled:"Divisão cancelada",deleted:"Divisão excluída",reminders_scheduled:"Lembretes preparados"} as Record<string,string>)[v]??v.replace(/_/g," ")}
function friendlyError(error: unknown){const message=error instanceof Error?error.message:typeof error==="string"?error:"";if(message.includes("Há pagamentos recebidos"))return "Esta divisão já recebeu pagamentos. Para preservar o histórico, cancele sem remover o lançamento.";if(message.includes("Divisão encerrada"))return "Esta divisão já foi encerrada.";if(message.includes("reminders_disabled"))return "Os lembretes estão desativados nesta divisão.";return message||"Não consegui concluir";}
