// GERADO POR scripts/sync-finance-core.mjs — NÃO EDITAR À MÃO.
// Fonte canônica: src/lib/engine/<module>.ts (finance_contract.v4)
export const FINANCE_CONTRACT_VERSION = "finance_contract.v4";
export * from "./facts.ts";
export * from "./canonicalFacts.ts";
export * from "./engineEnvelope.ts";
export * from "./brazilianCalendar.ts";
export * from "./ninoClock.ts";
export * from "./financialComparison.ts";
export * from "./financialPerformance.ts";
export * from "./advisorRelevance.ts";
export * from "./merchant.ts";
export * from "./merchantIntelligence.ts";
export * from "./behaviorChange.ts";
export * from "./recurringDiscovery.ts";
export * from "./costStructure.ts";
export * from "./anomalies.ts";
export * from "./emotionFinance.ts";
export * from "./savingsOpportunities.ts";
export * from "./financialEvolution.ts";
export * from "./bridges.ts";
export * from "./spendingRhythm.ts";
export * from "./dailyAverage.ts";
export * from "./cardExposure.ts";
export * from "./incomeProjection.ts";
export * from "./commitmentAgenda.ts";
export * from "./debtStatus.ts";
export * from "./categoryProjection.ts";
export * from "./metrics.ts";
export * from "./categoryGoalStrategy.ts";
export * from "./goalPerformanceAssessment.ts";
export * from "./longitudinal.ts";
export * from "./wealthOpportunity.ts";
export * from "./recurringSchedule.ts";
export type { DateRange, Trend } from "./spendingRhythm.ts";
export { daysInclusive, formatRangeShort } from "./spendingRhythm.ts";
