-- ONE-TIME pre-migration logical compaction for Meu Nino.
-- Run on the source database before copying production data to a fresh Supabase project.
-- It intentionally does NOT VACUUM FULL: the fresh target database reclaims physical bloat naturally.

BEGIN;

-- Preserve a compact audit of the legacy category-engine retry storm observed
-- before the semantic terminal-attempt fix deployed on 2026-08-25 16:53 UTC.
CREATE TABLE IF NOT EXISTS public.category_decision_legacy_compaction (
  user_id uuid NOT NULL,
  transaction_id uuid NOT NULL,
  engine_version text NOT NULL,
  reason_code text,
  rows_collapsed bigint NOT NULL,
  first_at timestamptz,
  last_at timestamptz,
  compacted_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, transaction_id, engine_version)
);

INSERT INTO public.category_decision_legacy_compaction(
  user_id,transaction_id,engine_version,reason_code,rows_collapsed,first_at,last_at,compacted_at
)
SELECT
  d.user_id,d.transaction_id,d.engine_version,
  min(d.reason_code) AS reason_code,
  count(*) AS rows_collapsed,
  min(d.created_at),max(d.created_at),now()
FROM public.category_decisions d
WHERE d.transaction_id IS NOT NULL
  AND d.action='leave_unresolved'
  AND d.source='none'
  AND d.created_at < timestamptz '2026-08-25 16:54:00+00'
GROUP BY d.user_id,d.transaction_id,d.engine_version
ON CONFLICT (user_id,transaction_id,engine_version) DO UPDATE
SET reason_code=excluded.reason_code,
    rows_collapsed=excluded.rows_collapsed,
    first_at=excluded.first_at,
    last_at=excluded.last_at,
    compacted_at=now();

-- Remove only legacy no-op decisions that are not referenced by a transaction or
-- a terminal classification attempt. Referenced decisions are preserved exactly.
DELETE FROM public.category_decisions d
WHERE d.transaction_id IS NOT NULL
  AND d.action='leave_unresolved'
  AND d.source='none'
  AND d.created_at < timestamptz '2026-08-25 16:54:00+00'
  AND NOT EXISTS (SELECT 1 FROM public.transactions t WHERE t.category_decision_id=d.id)
  AND NOT EXISTS (SELECT 1 FROM public.category_classification_attempts a WHERE a.decision_id=d.id);

-- Evidence: keep one copy of identical material evidence per situation/day.
WITH ranked AS (
  SELECT id,
         row_number() OVER (
           PARTITION BY situation_id, created_at::date, evidence_type, metric_key,
                        value, contribution_amount, contribution_pct, confidence, metadata
           ORDER BY created_at DESC, id DESC
         ) AS rn
  FROM public.financial_situation_evidence
)
DELETE FROM public.financial_situation_evidence e
USING ranked r
WHERE e.id=r.id AND r.rn>1;

-- Events: keep one copy of an identical state transition per situation/day.
WITH ranked AS (
  SELECT id,
         row_number() OVER (
           PARTITION BY situation_id, occurred_at::date, event_type, from_status,
                        to_status, delta_amount, narrative, metadata
           ORDER BY occurred_at DESC, id DESC
         ) AS rn
  FROM public.financial_situation_events
)
DELETE FROM public.financial_situation_events e
USING ranked r
WHERE e.id=r.id AND r.rn>1;

-- Snapshots: preserve every distinct material diagnosis, but remove repeated
-- copies generated by the 30-minute scheduler. Current rows win ties.
WITH ranked AS (
  SELECT id,
         row_number() OVER (
           PARTITION BY user_id,run_mode,as_of,overall_state,primary_situation_id,
                        supporting_situation_ids,primary_action_id,forecast,data_quality,
                        confidence,rationale,payload,contract_version
           ORDER BY is_current DESC,created_at DESC,id DESC
         ) AS rn
  FROM public.nino_diagnosis_snapshots
)
DELETE FROM public.nino_diagnosis_snapshots s
USING ranked r
WHERE s.id=r.id AND r.rn>1;

-- Cron history is operational telemetry; seven days is sufficient for debugging.
DELETE FROM cron.job_run_details
WHERE end_time < now()-interval '7 days';

ANALYZE public.category_decisions;
ANALYZE public.financial_situation_evidence;
ANALYZE public.financial_situation_events;
ANALYZE public.nino_diagnosis_snapshots;

COMMIT;
