// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-transactions.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.6";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (ou VITE_SUPABASE_URL) \xE9 obrigat\xF3rio");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS ou SUPABASE_ANON_KEY \xE9 obrigat\xF3rio");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser exige um token OAuth verificado");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/engine/facts.ts
function isHardBankAnchor(s) {
  if (s.status && s.status !== "confirmed") return false;
  if (s.anchor_kind) return s.anchor_kind === "bank_confirmed";
  return Boolean(s.source_document_id);
}
var BANK_POSTING_SOURCES = /* @__PURE__ */ new Set(["statement", "bank", "ofx", "reconciliation"]);
function hasBankPosting(t) {
  if (!t.posted_at) return false;
  return BANK_POSTING_SOURCES.has(String(t.posted_at_source ?? "inferred"));
}
function cashDateOf(t) {
  if (hasBankPosting(t)) return String(t.posted_at);
  return t.competence_date || t.occurred_at;
}
function txOrigin(t) {
  if (t.credit_card_id) return "credit_card";
  const pm = (t.payment_method ?? "").toString().toLowerCase();
  if (pm === "credit_card") return "credit_card";
  return "account";
}
var round2 = (n) => Math.round((n + Number.EPSILON) * 100) / 100;
function computeAccountBalances(accounts, txs, snapshots = [], opts) {
  const map = {};
  const cutoff = {};
  const asOf = opts?.asOf ?? null;
  for (const a of accounts) map[a.id] = Number(a.opening_balance || 0);
  const anchors = snapshots.filter((x) => isHardBankAnchor(x)).filter((x) => !asOf || x.balance_date <= asOf).sort((a, b) => a.balance_date.localeCompare(b.balance_date));
  for (const s of anchors) {
    map[s.account_id] = Number(s.balance);
    cutoff[s.account_id] = s.balance_date;
  }
  const withinWindow = (accountId, t) => {
    const d = cashDateOf(t);
    if (cutoff[accountId] && d <= cutoff[accountId]) return false;
    if (asOf && d > asOf) return false;
    return true;
  };
  for (const t of txs) {
    if (t.status !== "confirmed") continue;
    if (t.type === "transfer") continue;
    if (txOrigin(t) !== "account") continue;
    if (!t.account_id) continue;
    if (!withinWindow(t.account_id, t)) continue;
    const amt = Number(t.amount || 0);
    if (!map[t.account_id] && map[t.account_id] !== 0) map[t.account_id] = 0;
    if (t.type === "income") map[t.account_id] += amt;
    else if (t.type === "expense") map[t.account_id] -= amt;
  }
  const groups = {};
  for (const t of txs) {
    if (t.type !== "transfer" || t.status !== "confirmed" || !t.transfer_group_id) continue;
    (groups[t.transfer_group_id] ||= []).push(t);
  }
  for (const legs of Object.values(groups)) {
    if (legs.length < 2) continue;
    const sorted = [...legs].sort((a, b) => a.id.localeCompare(b.id));
    const src = sorted[0];
    const dst = sorted[1];
    if (!withinWindow(src.account_id, src)) continue;
    if (!withinWindow(dst.account_id, dst)) continue;
    const amt = Number(src.amount || 0);
    map[src.account_id] = (map[src.account_id] || 0) - amt;
    map[dst.account_id] = (map[dst.account_id] || 0) + amt;
  }
  for (const k of Object.keys(map)) map[k] = round2(map[k]);
  return map;
}
function computeTotalCash(accounts, txs, snapshots = [], opts) {
  const bals = computeAccountBalances(accounts, txs, snapshots, opts);
  return round2(Object.values(bals).reduce((a, b) => a + b, 0));
}
function isInMonth(dateStr, ym) {
  return dateStr.startsWith(ym);
}
var EXCLUDED_MOVEMENT_KINDS = /* @__PURE__ */ new Set([
  "internal_transfer",
  "investment_application",
  "investment_redemption",
  "investment_yield",
  "loan_proceeds",
  "external_transfer_in",
  "external_transfer_out"
]);
function isRealMonthlyMovement(t) {
  if (t.status !== "confirmed") return false;
  if (t.type === "transfer") return false;
  if (t.transfer_group_id) return false;
  const mk = (t.movement_kind ?? "transaction").toString();
  if (EXCLUDED_MOVEMENT_KINDS.has(mk)) return false;
  if (mk !== "transaction") return false;
  if (t.settles_card_id) return false;
  return true;
}
function behavioralMetricAmount(t, metric) {
  if (t.status !== "confirmed" || t.type === "transfer") return 0;
  const mk = (t.movement_kind ?? "transaction").toString();
  if (mk === "refund") {
    if (metric !== "expense") return 0;
    if (t.type !== "income") return 0;
    if (t.transfer_group_id) return 0;
    return -Number(t.amount || 0);
  }
  if (!isRealMonthlyMovement(t) || t.type !== metric) return 0;
  return Number(t.amount || 0);
}
function computeMonthlyTotals(txs, ym) {
  let income = 0, expense = 0;
  for (const t of txs) {
    if (!isInMonth(t.occurred_at, ym)) continue;
    income += behavioralMetricAmount(t, "income");
    expense += behavioralMetricAmount(t, "expense");
  }
  return { income: round2(income), expense: round2(expense), net: round2(income - expense) };
}
function computeBehavioralExpense(txs, range) {
  let expense = 0;
  for (const t of txs) {
    if (t.occurred_at < range.start || t.occurred_at > range.end) continue;
    expense += behavioralMetricAmount(t, "expense");
  }
  return round2(expense);
}
function buildRefundAttribution(txs) {
  const categoryById = /* @__PURE__ */ new Map();
  for (const t of txs) categoryById.set(t.id, t.category_id ?? null);
  const attribution = /* @__PURE__ */ new Map();
  for (const t of txs) {
    const original = t.refund_of_transaction_id;
    if (!original) continue;
    if (!categoryById.has(original)) continue;
    attribution.set(t.id, categoryById.get(original) ?? null);
  }
  return attribution;
}
function effectiveCategoryId(t, attribution) {
  if (attribution?.has(t.id)) return attribution.get(t.id) ?? null;
  return t.category_id ?? null;
}
function computeCategoryBreakdown(txs, categories, ym, type = "expense") {
  const byCat = {};
  const attribution = buildRefundAttribution(txs);
  for (const t of txs) {
    if (!isInMonth(t.occurred_at, ym)) continue;
    const signed = behavioralMetricAmount(t, type);
    if (signed === 0) continue;
    const key = effectiveCategoryId(t, attribution) ?? "__none__";
    byCat[key] = (byCat[key] || 0) + signed;
  }
  const catName = (id) => id === "__none__" ? "Sem categoria" : categories.find((c) => c.id === id)?.name ?? "Categoria removida";
  const total = round2(Object.values(byCat).reduce((a, b) => a + b, 0));
  return Object.entries(byCat).map(([id, v]) => ({ id, name: catName(id), amount: round2(v), share: total > 0 ? round2(v) / total : 0 })).filter((row) => row.amount !== 0).sort((a, b) => b.amount - a.amount);
}
var SP_TZ = "America/Sao_Paulo";
function todaySP(now = /* @__PURE__ */ new Date()) {
  const parts = new Intl.DateTimeFormat("en-CA", {
    timeZone: SP_TZ,
    year: "numeric",
    month: "2-digit",
    day: "2-digit"
  }).format(now);
  return parts;
}
function currentMonthYM(now = /* @__PURE__ */ new Date()) {
  return todaySP(now).slice(0, 7);
}

// src/lib/engine/bridges.ts
var BRIDGE_FORMULA_VERSION = "cash_bridge.v1";
var NEUTRAL = { performanceImpact: 0 };
var MOVEMENT_SEMANTICS = {
  income: {
    cashImpact: 1,
    performanceImpact: 1,
    investmentImpact: 0,
    debtImpact: 0,
    netWorthImpact: 1,
    bridgeLine: "operational_income",
    label: "Receita",
    explanation: "Dinheiro que entrou na conta e conta como receita da sua rotina."
  },
  expense: {
    cashImpact: -1,
    performanceImpact: -1,
    investmentImpact: 0,
    debtImpact: 0,
    netWorthImpact: -1,
    bridgeLine: "operational_account_expense",
    label: "Gasto",
    explanation: "Dinheiro que saiu da conta e conta como gasto da sua rotina."
  },
  card_expense: {
    cashImpact: 0,
    performanceImpact: -1,
    investmentImpact: 0,
    debtImpact: 1,
    netWorthImpact: -1,
    bridgeLine: "operational_account_expense",
    label: "Compra no cart\xE3o",
    explanation: "Conta como consumo agora e aumenta a fatura, mas s\xF3 sai da conta quando voc\xEA pagar a fatura."
  },
  refund: {
    ...NEUTRAL,
    cashImpact: 1,
    performanceImpact: 1,
    investmentImpact: 0,
    debtImpact: 0,
    netWorthImpact: 1,
    bridgeLine: "refunds_and_reimbursements",
    label: "Estorno / reembolso",
    explanation: "Devolu\xE7\xE3o de um valor: entra na conta e abate o gasto original."
  },
  internal_transfer: {
    cashImpact: 0,
    performanceImpact: 0,
    investmentImpact: 0,
    debtImpact: 0,
    netWorthImpact: 0,
    bridgeLine: "internal_transfers_net",
    label: "Transfer\xEAncia entre suas contas",
    explanation: "Muda o dinheiro de lugar. N\xE3o \xE9 receita nem gasto, e n\xE3o altera seu patrim\xF4nio."
  },
  external_transfer_in: {
    cashImpact: 1,
    performanceImpact: 0,
    investmentImpact: 0,
    debtImpact: 0,
    netWorthImpact: 1,
    bridgeLine: "external_transfers_in",
    label: "Transfer\xEAncia recebida",
    explanation: "Entrou dinheiro de terceiro. Aumenta o saldo, mas n\xE3o \xE9 receita da sua rotina."
  },
  external_transfer_out: {
    cashImpact: -1,
    performanceImpact: 0,
    investmentImpact: 0,
    debtImpact: 0,
    netWorthImpact: -1,
    bridgeLine: "external_transfers_out",
    label: "Transfer\xEAncia enviada",
    explanation: "Saiu dinheiro para terceiro. Reduz o saldo, mas n\xE3o \xE9 gasto da sua rotina."
  },
  investment_application: {
    cashImpact: -1,
    performanceImpact: 0,
    investmentImpact: 1,
    debtImpact: 0,
    netWorthImpact: 0,
    bridgeLine: "investment_applications",
    label: "Aplica\xE7\xE3o",
    explanation: "Saiu da conta e entrou no investimento. Seu patrim\xF4nio n\xE3o muda."
  },
  investment_redemption: {
    cashImpact: 1,
    performanceImpact: 0,
    investmentImpact: -1,
    debtImpact: 0,
    netWorthImpact: 0,
    bridgeLine: "investment_redemptions",
    label: "Resgate",
    explanation: "Saiu do investimento e entrou na conta. Seu patrim\xF4nio n\xE3o muda."
  },
  investment_yield: {
    cashImpact: 1,
    performanceImpact: 0,
    investmentImpact: 0,
    debtImpact: 0,
    netWorthImpact: 1,
    bridgeLine: "investment_yield_cash",
    label: "Rendimento creditado",
    explanation: "Rendimento pago na conta. Aumenta caixa e patrim\xF4nio, sem virar receita da rotina nem alterar o principal do ativo."
  },
  loan_proceeds: {
    cashImpact: 1,
    performanceImpact: 0,
    investmentImpact: 0,
    debtImpact: 1,
    netWorthImpact: 0,
    bridgeLine: "loan_proceeds",
    label: "Cr\xE9dito de empr\xE9stimo",
    explanation: "Entrou dinheiro na conta, mas criou uma d\xEDvida do mesmo valor. N\xE3o \xE9 receita."
  },
  debt_payment: {
    cashImpact: -1,
    performanceImpact: 0,
    investmentImpact: 0,
    debtImpact: -1,
    netWorthImpact: 0,
    bridgeLine: "debt_principal_payments",
    label: "Amortiza\xE7\xE3o de d\xEDvida",
    explanation: "Saiu da conta e reduziu sua d\xEDvida no mesmo valor. N\xE3o \xE9 gasto novo."
  },
  card_payment: {
    cashImpact: -1,
    performanceImpact: 0,
    investmentImpact: 0,
    debtImpact: -1,
    netWorthImpact: 0,
    bridgeLine: "card_payments",
    label: "Pagamento de fatura",
    explanation: "Saiu da conta e reduziu a fatura. O consumo j\xE1 foi contado na data da compra."
  },
  fee: {
    cashImpact: -1,
    performanceImpact: -1,
    investmentImpact: 0,
    debtImpact: 0,
    netWorthImpact: -1,
    bridgeLine: "debt_interest_and_fees",
    label: "Tarifa",
    explanation: "Custo banc\xE1rio: sai da conta e reduz seu patrim\xF4nio."
  },
  interest: {
    cashImpact: -1,
    performanceImpact: -1,
    investmentImpact: 0,
    debtImpact: 0,
    netWorthImpact: -1,
    bridgeLine: "debt_interest_and_fees",
    label: "Juros",
    explanation: "Custo do cr\xE9dito: sai da conta e reduz seu patrim\xF4nio."
  },
  adjustment: {
    cashImpact: 1,
    performanceImpact: 0,
    investmentImpact: 0,
    debtImpact: 0,
    netWorthImpact: 1,
    bridgeLine: "adjustments",
    label: "Ajuste de concilia\xE7\xE3o",
    explanation: "Corre\xE7\xE3o para o saldo do app bater com o extrato do banco."
  }
};
function semanticsOf(t) {
  if (t.settles_card_id) return MOVEMENT_SEMANTICS.card_payment;
  const mk = String(t.movement_kind ?? "").trim();
  if (mk && mk !== "transaction" && MOVEMENT_SEMANTICS[mk]) return MOVEMENT_SEMANTICS[mk];
  if (t.type === "transfer") return MOVEMENT_SEMANTICS.internal_transfer;
  if (t.type === "income") return MOVEMENT_SEMANTICS.income;
  if (txOrigin(t) === "credit_card") return MOVEMENT_SEMANTICS.card_expense;
  return MOVEMENT_SEMANTICS.expense;
}
function dayBefore(iso2) {
  const [y, m, d] = iso2.split("-").map(Number);
  const dt = new Date(Date.UTC(y, (m || 1) - 1, d || 1));
  dt.setUTCDate(dt.getUTCDate() - 1);
  return dt.toISOString().slice(0, 10);
}
var LINE_LABELS = {
  operational_income: "Receitas recebidas",
  operational_account_expense: "Gastos pagos pela conta",
  investment_redemptions: "Resgates de investimentos",
  investment_applications: "Aplica\xE7\xF5es em investimentos",
  investment_yield_cash: "Rendimentos creditados",
  external_transfers_in: "Transfer\xEAncias recebidas",
  external_transfers_out: "Transfer\xEAncias enviadas",
  internal_transfers_net: "Transfer\xEAncias entre suas contas",
  loan_proceeds: "Empr\xE9stimos creditados",
  debt_principal_payments: "Pagamentos de d\xEDvidas",
  debt_interest_and_fees: "Juros e tarifas",
  card_payments: "Pagamentos de fatura",
  refunds_and_reimbursements: "Estornos e reembolsos",
  adjustments: "Ajustes e concilia\xE7\xF5es",
  unexplained: "Diferen\xE7a ainda n\xE3o explicada"
};
function computeCashBridge(input) {
  const { period } = input;
  const scope = input.accountId ?? null;
  const accounts = scope ? input.accounts.filter((a) => a.id === scope) : input.accounts;
  const snapshots = (input.snapshots ?? []).filter((s) => !scope || s.account_id === scope);
  const openingCash = computeTotalCash(accounts, input.txs, snapshots, { asOf: dayBefore(period.start) });
  const confirmedClosingCash = computeTotalCash(accounts, input.txs, snapshots, { asOf: period.end });
  const buckets = /* @__PURE__ */ new Map();
  const bump = (line, amount, direction) => {
    const cur = buckets.get(line) ?? { amount: 0, count: 0, direction };
    cur.amount += Math.abs(amount);
    cur.count += 1;
    cur.direction = direction;
    buckets.set(line, cur);
  };
  let transactionCount = 0;
  let inferredCashDateCount = 0;
  let internalNet = 0;
  const transferGroups = /* @__PURE__ */ new Map();
  for (const t of input.txs) {
    if (t.status !== "confirmed") continue;
    if (txOrigin(t) !== "account") continue;
    const d = cashDateOf(t);
    if (d < period.start || d > period.end) continue;
    if (scope && t.account_id !== scope && t.type !== "transfer") continue;
    if (t.type === "transfer" && t.transfer_group_id) {
      const arr = transferGroups.get(t.transfer_group_id) ?? [];
      arr.push(t);
      transferGroups.set(t.transfer_group_id, arr);
      continue;
    }
    const sem = semanticsOf(t);
    if (sem.cashImpact === 0) continue;
    transactionCount += 1;
    if (!t.posted_at || t.posted_at_source === "inferred") inferredCashDateCount += 1;
    bump(sem.bridgeLine, Number(t.amount || 0), sem.cashImpact);
  }
  for (const legs of transferGroups.values()) {
    if (legs.length < 2) continue;
    const sorted = [...legs].sort((a, b) => a.id.localeCompare(b.id));
    const [src, dst] = sorted;
    const amt = Number(src.amount || 0);
    if (!scope) continue;
    if (src.account_id === scope) internalNet -= amt;
    if (dst.account_id === scope) internalNet += amt;
  }
  if (internalNet !== 0) {
    bump("internal_transfers_net", internalNet, internalNet > 0 ? 1 : -1);
  }
  const get = (line) => round2(buckets.get(line)?.amount ?? 0);
  const operationalIncome = get("operational_income");
  const operationalAccountExpense = get("operational_account_expense");
  const investmentRedemptions = get("investment_redemptions");
  const investmentApplications = get("investment_applications");
  const investmentYieldCash = get("investment_yield_cash");
  const externalTransfersIn = get("external_transfers_in");
  const externalTransfersOut = get("external_transfers_out");
  const loanProceeds = get("loan_proceeds");
  const debtPrincipalPayments = get("debt_principal_payments");
  const debtInterestAndFees = get("debt_interest_and_fees");
  const cardPayments = get("card_payments");
  const refundsAndReimbursements = get("refunds_and_reimbursements");
  const internalTransfersNet = round2(internalNet);
  const movementsSum = round2(
    operationalIncome - operationalAccountExpense + investmentRedemptions - investmentApplications + investmentYieldCash + externalTransfersIn - externalTransfersOut + internalTransfersNet + loanProceeds - debtPrincipalPayments - debtInterestAndFees - cardPayments + refundsAndReimbursements + get("adjustments")
  );
  const adjustments = get("adjustments");
  const calculatedClosingCash = round2(openingCash + movementsSum);
  const unexplainedDifference = round2(confirmedClosingCash - calculatedClosingCash);
  const reconciliationDifference = unexplainedDifference;
  const anchors = snapshots.filter((s) => !s.status || s.status === "confirmed").filter((s) => s.balance_date >= period.start && s.balance_date <= period.end);
  const lastConfirmed = [...snapshots].filter((s) => !s.status || s.status === "confirmed").sort((a, b) => a.balance_date.localeCompare(b.balance_date)).pop();
  let confidence = "high";
  const tolerance = Math.max(50, Math.abs(confirmedClosingCash) * 0.05);
  if (Math.abs(unexplainedDifference) > 0.01) confidence = "medium";
  if (Math.abs(unexplainedDifference) > tolerance) confidence = "low";
  const lines = [
    ["operational_income", operationalIncome, 1],
    ["operational_account_expense", operationalAccountExpense, -1],
    ["refunds_and_reimbursements", refundsAndReimbursements, 1],
    ["investment_redemptions", investmentRedemptions, 1],
    ["investment_applications", investmentApplications, -1],
    ["investment_yield_cash", investmentYieldCash, 1],
    ["external_transfers_in", externalTransfersIn, 1],
    ["external_transfers_out", externalTransfersOut, -1],
    ["internal_transfers_net", Math.abs(internalTransfersNet), internalTransfersNet >= 0 ? 1 : -1],
    ["loan_proceeds", loanProceeds, 1],
    ["card_payments", cardPayments, -1],
    ["debt_principal_payments", debtPrincipalPayments, -1],
    ["debt_interest_and_fees", debtInterestAndFees, -1],
    ["adjustments", Math.abs(adjustments), adjustments >= 0 ? 1 : -1],
    ["unexplained", Math.abs(unexplainedDifference), unexplainedDifference >= 0 ? 1 : -1]
  ].filter(([, amount]) => Math.abs(amount) > 5e-3).map(([key, amount, direction]) => ({
    key,
    label: LINE_LABELS[key],
    amount: round2(amount),
    direction,
    count: buckets.get(key)?.count ?? 0
  }));
  return {
    formulaVersion: BRIDGE_FORMULA_VERSION,
    period,
    accountId: scope,
    openingCash,
    operationalIncome,
    operationalAccountExpense,
    investmentRedemptions,
    investmentApplications,
    externalTransfersIn,
    externalTransfersOut,
    internalTransfersNet,
    loanProceeds,
    debtPrincipalPayments,
    debtInterestAndFees,
    cardPayments,
    refundsAndReimbursements,
    investmentYieldCash,
    adjustments,
    unexplainedDifference,
    calculatedClosingCash,
    confirmedClosingCash,
    reconciliationDifference,
    confidence,
    lines,
    evidence: {
      transactionCount,
      inferredCashDateCount,
      snapshotAnchorsInPeriod: anchors.length,
      lastConfirmedSnapshot: lastConfirmed?.balance_date ?? null
    }
  };
}
function computePeriodPerformance(txs, period) {
  let income = 0;
  let refunds = 0;
  for (const t of txs) {
    if (t.status !== "confirmed") continue;
    if (t.occurred_at < period.start || t.occurred_at > period.end) continue;
    const sem = semanticsOf(t);
    if (sem.performanceImpact !== 1) continue;
    if (sem.bridgeLine === "refunds_and_reimbursements") {
      refunds += Number(t.amount || 0);
      continue;
    }
    income += Number(t.amount || 0);
  }
  const operationalIncome = round2(income);
  const operationalExpense = round2(computeBehavioralExpense(txs, period));
  const operationalResult = round2(operationalIncome - operationalExpense);
  return {
    period,
    operationalIncome,
    operationalExpense,
    operationalResult,
    operationalGap: operationalResult < 0 ? round2(-operationalResult) : 0,
    savingsRate: operationalIncome > 0 ? round2(operationalResult / operationalIncome) : null,
    refunds: round2(refunds)
  };
}
var money = (n) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(n || 0));
function explainBalanceChange(bridge, performance) {
  const steps = [];
  steps.push(`Voc\xEA come\xE7ou o per\xEDodo com ${money(bridge.openingCash)} em conta.`);
  if (bridge.operationalIncome > 0) steps.push(`Recebeu ${money(bridge.operationalIncome)} de receitas.`);
  if (bridge.operationalAccountExpense > 0) steps.push(`Pagou ${money(bridge.operationalAccountExpense)} de gastos pela conta.`);
  if (bridge.refundsAndReimbursements > 0) steps.push(`Recebeu ${money(bridge.refundsAndReimbursements)} em estornos e reembolsos.`);
  if (bridge.investmentRedemptions > 0) steps.push(`Resgatou ${money(bridge.investmentRedemptions)} dos investimentos.`);
  if (bridge.investmentApplications > 0) steps.push(`Aplicou ${money(bridge.investmentApplications)} em investimentos.`);
  if (bridge.externalTransfersIn > 0) steps.push(`Recebeu ${money(bridge.externalTransfersIn)} em transfer\xEAncias.`);
  if (bridge.externalTransfersOut > 0) steps.push(`Enviou ${money(bridge.externalTransfersOut)} em transfer\xEAncias.`);
  if (bridge.loanProceeds > 0) steps.push(`Recebeu ${money(bridge.loanProceeds)} de cr\xE9dito \u2014 isso \xE9 d\xEDvida, n\xE3o receita.`);
  if (bridge.cardPayments > 0) steps.push(`Pagou ${money(bridge.cardPayments)} de fatura do cart\xE3o (consumo j\xE1 contado antes).`);
  if (bridge.debtPrincipalPayments > 0) steps.push(`Amortizou ${money(bridge.debtPrincipalPayments)} de d\xEDvidas.`);
  if (bridge.debtInterestAndFees > 0) steps.push(`Pagou ${money(bridge.debtInterestAndFees)} de juros e tarifas.`);
  if (bridge.investmentYieldCash > 0) steps.push(`Recebeu ${money(bridge.investmentYieldCash)} de rendimentos creditados na conta.`);
  if (Math.abs(bridge.adjustments) > 0.01) {
    steps.push(
      bridge.adjustments > 0 ? `Somamos ${money(bridge.adjustments)} de ajuste de concilia\xE7\xE3o registrado por voc\xEA.` : `Descontamos ${money(Math.abs(bridge.adjustments))} de ajuste de concilia\xE7\xE3o registrado por voc\xEA.`
    );
  }
  if (Math.abs(bridge.unexplainedDifference) > 0.01) {
    steps.push(
      `Ainda faltam ${money(Math.abs(bridge.unexplainedDifference))} para os lan\xE7amentos explicarem o saldo confirmado \u2014 provavelmente h\xE1 movimentos n\xE3o importados nesse per\xEDodo.`
    );
  }
  steps.push(`Por isso terminou com ${money(bridge.confirmedClosingCash)} em conta.`);
  const gap = performance?.operationalGap ?? 0;
  const delta = round2(bridge.confirmedClosingCash - bridge.openingCash);
  let headline;
  let tone;
  if (gap > 0) {
    headline = `Gastos acima das receitas: ${money(gap)}`;
    tone = "attention";
  } else if (delta >= 0) {
    headline = `Seu saldo em conta cresceu ${money(delta)}`;
    tone = "positive";
  } else {
    headline = `Voc\xEA usou ${money(Math.abs(delta))} de recursos acumulados`;
    tone = "neutral";
  }
  const body = [
    steps.join(" "),
    gap > 0 && bridge.confirmedClosingCash > 0 ? "Sua conta continua positiva porque havia saldo anterior e/ou movimenta\xE7\xF5es patrimoniais." : null
  ].filter(Boolean).join(" ");
  return { headline, body, tone, steps, confidence: bridge.confidence };
}

// src/lib/engine/cardExposure.ts
var CARD_EXPOSURE_FORMULA_VERSION = "card_exposure.v2";
var CARD_CYCLE_VERSION = "card_cycle.v2";
var pad = (n) => String(n).padStart(2, "0");
var lastDayOf = (y, m1) => new Date(Date.UTC(y, m1, 0)).getUTCDate();
var iso = (y, m1, d) => `${y}-${pad(m1)}-${pad(d)}`;
function addMonths(y, m1, delta) {
  const zero = y * 12 + (m1 - 1) + delta;
  return [Math.floor(zero / 12), zero % 12 + 1];
}
function dayInMonth(y, m1, day) {
  return iso(y, m1, Math.min(Math.max(1, day), lastDayOf(y, m1)));
}
function addDaysISO(value, days) {
  const [y, m, d] = value.split("-").map(Number);
  const dt = new Date(Date.UTC(y, m - 1, d + days));
  return iso(dt.getUTCFullYear(), dt.getUTCMonth() + 1, dt.getUTCDate());
}
function cycleFor(card, dateISO) {
  const [y0, m0, d0] = String(dateISO).slice(0, 10).split("-").map(Number);
  const closingDay = Number(card?.closing_day ?? 0);
  const dueDayRaw = Number(card?.due_day ?? 0);
  const fallback = !(closingDay >= 1 && closingDay <= 31);
  if (!y0 || !m0 || !d0) {
    const now = /* @__PURE__ */ new Date();
    return cycleFor(card, iso(now.getUTCFullYear(), now.getUTCMonth() + 1, now.getUTCDate()));
  }
  if (fallback) {
    const end = dayInMonth(y0, m0, 31);
    const dueDay2 = dueDayRaw >= 1 ? dueDayRaw : lastDayOf(y0, m0);
    return {
      competence: `${y0}-${pad(m0)}`,
      period_start: iso(y0, m0, 1),
      period_end: end,
      closing_date: end,
      due_date: dayInMonth(y0, m0, dueDay2),
      fallback: true
    };
  }
  const closingThis = Math.min(closingDay, lastDayOf(y0, m0));
  const [cy, cm] = d0 <= closingThis ? [y0, m0] : addMonths(y0, m0, 1);
  const closing = dayInMonth(cy, cm, closingDay);
  const [py, pm] = addMonths(cy, cm, -1);
  const periodStart = addDaysISO(dayInMonth(py, pm, closingDay), 1);
  const dueDay = dueDayRaw >= 1 && dueDayRaw <= 31 ? dueDayRaw : closingDay;
  const [dy, dm] = dueDay > closingDay ? [cy, cm] : addMonths(cy, cm, 1);
  const due = dayInMonth(dy, dm, dueDay);
  return {
    competence: due.slice(0, 7),
    period_start: periodStart,
    period_end: closing,
    closing_date: closing,
    due_date: due,
    fallback: false
  };
}
function openCycleOf(card, todayISO2) {
  return cycleFor(card, todayISO2);
}
var SETTLED_STATUSES = /* @__PURE__ */ new Set(["paid", "settled", "closed_paid"]);
var CLOSED_STATUSES = /* @__PURE__ */ new Set(["paid", "settled", "closed", "closed_paid", "approved"]);
var DEAD_INSTALLMENTS = /* @__PURE__ */ new Set(["paid", "refunded", "cancelled", "reversed", "anticipated"]);
var emptyFigure = () => ({ amount: 0, source: "none", status: null, statedTotal: 0, paidAmount: 0 });
function isAuthoritativeCardStatement(statement) {
  const status = String(statement.status ?? "").toLowerCase();
  if (SETTLED_STATUSES.has(status) || CLOSED_STATUSES.has(status)) return true;
  return Math.abs(Number(statement.stated_total ?? 0)) > 5e-3 || Math.abs(Number(statement.outstanding_amount ?? 0)) > 5e-3 || Math.abs(Number(statement.paid_amount ?? 0)) > 5e-3;
}
function nextCompetence(ym) {
  const [y, m] = ym.split("-").map(Number);
  if (!y || !m) return ym;
  return m === 12 ? `${y + 1}-01` : `${y}-${String(m + 1).padStart(2, "0")}`;
}
function ymOf(value) {
  const v = String(value ?? "");
  return /^\d{4}-\d{2}/.test(v) ? v.slice(0, 7) : null;
}
function estimateFromTxs(txs, cardId, ym) {
  let total = 0;
  for (const t of txs) {
    if (t.credit_card_id !== cardId) continue;
    if (t.settles_card_id) continue;
    if (t.status && t.status !== "confirmed") continue;
    if (ymOf(t.competence_date) !== ym) continue;
    const amt = Number(t.amount || 0);
    total += t.type === "income" ? -amt : amt;
  }
  return round2(Math.max(0, total));
}
function installmentsOfCompetence(installments, txs, cardId, ym) {
  const ledgerIds = new Set(
    txs.filter((tx) => tx.credit_card_id === cardId && ymOf(tx.competence_date) === ym).map((tx) => tx.id).filter((id) => Boolean(id))
  );
  let total = 0;
  for (const inst of installments) {
    if (inst.credit_card_id !== cardId) continue;
    if (inst.absorbed_by_statement_id) continue;
    if (DEAD_INSTALLMENTS.has((inst.status ?? "").toString())) continue;
    if (ymOf(inst.competence_month) !== ym) continue;
    if (inst.legacy_transaction_id && ledgerIds.has(inst.legacy_transaction_id)) continue;
    total += Number(inst.amount || 0);
  }
  return round2(Math.max(0, total));
}
function estimateFromCycle(txs, cardId, cycle) {
  let total = 0;
  for (const t of txs) {
    if (t.credit_card_id !== cardId) continue;
    if (t.settles_card_id) continue;
    if (t.status && t.status !== "confirmed") continue;
    const day = String(t.occurred_at ?? "").slice(0, 10);
    if (!day || day < cycle.period_start || day > cycle.period_end) continue;
    const amt = Number(t.amount || 0);
    total += t.type === "income" ? -amt : amt;
  }
  return round2(Math.max(0, total));
}
function figureFromStatement(statement) {
  const status = (statement.status ?? "").toString() || null;
  const stated = round2(Number(statement.stated_total ?? 0));
  const paid = round2(Number(statement.paid_amount ?? 0));
  const outstanding = statement.outstanding_amount == null ? round2(Math.max(0, stated - paid)) : round2(Number(statement.outstanding_amount));
  const inconsistent = status === "needs_review" || round2(Number(statement.reconciliation_difference ?? 0)) !== 0;
  return {
    amount: SETTLED_STATUSES.has(status ?? "") ? 0 : outstanding,
    source: inconsistent ? "partial" : "official",
    status,
    statedTotal: stated,
    paidAmount: paid,
    purchasesAmount: null,
    installmentsAmount: null
  };
}
function estimatedFigure(txs, installments, cardId, ym) {
  const purchases = estimateFromTxs(txs, cardId, ym);
  const contracted = installmentsOfCompetence(installments, txs, cardId, ym);
  const total = round2(purchases + contracted);
  return {
    ...emptyFigure(),
    amount: total,
    source: total > 0 ? "estimated" : "unavailable",
    purchasesAmount: purchases,
    installmentsAmount: contracted
  };
}
function computeCardExposure(input) {
  const { cardIds, statements, installments, txs, currentYM } = input;
  const nextYM = nextCompetence(currentYM);
  const today = input.todayISO ?? `${currentYM}-01`;
  const cycleConfig = /* @__PURE__ */ new Map();
  for (const c of input.cards ?? []) if (c.id) cycleConfig.set(c.id, c);
  const result = {};
  const ids = new Set(cardIds);
  for (const s of statements) ids.add(s.credit_card_id);
  for (const i of installments) ids.add(i.credit_card_id);
  for (const cardId of ids) {
    const cardStatements = statements.filter((s) => s.credit_card_id === cardId);
    const byYM = /* @__PURE__ */ new Map();
    for (const s of cardStatements) {
      const ym = ymOf(s.competence_month);
      if (ym) byYM.set(ym, s);
    }
    const currentCandidate = byYM.get(currentYM);
    const currentRow = currentCandidate && isAuthoritativeCardStatement(currentCandidate) ? currentCandidate : void 0;
    const current = currentRow ? figureFromStatement(currentRow) : estimatedFigure(txs, installments, cardId, currentYM);
    const nextCandidate = byYM.get(nextYM);
    const nextRow = nextCandidate && isAuthoritativeCardStatement(nextCandidate) ? nextCandidate : void 0;
    const next = nextRow ? figureFromStatement(nextRow) : estimatedFigure(txs, installments, cardId, nextYM);
    let lastClosedYM = "";
    for (const [ym, s] of byYM) {
      if (isAuthoritativeCardStatement(s) && CLOSED_STATUSES.has((s.status ?? "").toString()) && ym > lastClosedYM) lastClosedYM = ym;
    }
    let futureInstallments = 0;
    for (const inst of installments) {
      if (inst.credit_card_id !== cardId) continue;
      if (DEAD_INSTALLMENTS.has((inst.status ?? "").toString())) continue;
      if (inst.absorbed_by_statement_id) continue;
      const ym = ymOf(inst.competence_month);
      if (!ym) continue;
      if (lastClosedYM && ym <= lastClosedYM) continue;
      if (ym <= currentYM) continue;
      const covering = byYM.get(ym);
      if (covering && isAuthoritativeCardStatement(covering) && SETTLED_STATUSES.has((covering.status ?? "").toString())) continue;
      futureInstallments += Number(inst.amount || 0);
    }
    const openStatementsDebt = cardStatements.reduce((sum, s) => {
      if (!isAuthoritativeCardStatement(s)) return sum;
      const status = (s.status ?? "").toString();
      if (SETTLED_STATUSES.has(status)) return sum;
      const fig = figureFromStatement(s);
      return sum + fig.amount;
    }, 0);
    const totalCardDebt = round2(openStatementsDebt + (currentRow ? 0 : current.amount));
    const cfg = cycleConfig.get(cardId);
    const openCycle = cfg && Number(cfg.closing_day ?? 0) >= 1 ? openCycleOf(cfg, today) : null;
    const forming = openCycle ? { ...emptyFigure(), amount: estimateFromCycle(txs, cardId, openCycle), source: "estimated" } : emptyFigure();
    result[cardId] = {
      cardId,
      currentStatement: current,
      nextStatement: next,
      formingStatement: forming,
      futureInstallments: round2(futureInstallments),
      totalCardDebt,
      needsReview: Boolean(
        currentRow && ((currentRow.status ?? "") === "needs_review" || round2(Number(currentRow.reconciliation_difference ?? 0)) !== 0)
      ),
      openCycle,
      formulaVersion: CARD_EXPOSURE_FORMULA_VERSION,
      cycleVersion: CARD_CYCLE_VERSION
    };
  }
  return result;
}
function totalCardDebtOf(exposures) {
  return round2(Object.values(exposures).reduce((sum, e) => sum + e.totalCardDebt, 0));
}
function totalFutureInstallmentsOf(exposures) {
  return round2(Object.values(exposures).reduce((sum, e) => sum + e.futureInstallments, 0));
}

// src/lib/engine/metrics.ts
var FINANCE_CONTRACT_VERSION = "financial_snapshot_contract.v8";

// src/lib/mcp/shared.ts
var ERROR_CONTRACT_VERSION = "edge_error.v1";
var RETRYABLE_CODES = /* @__PURE__ */ new Set([
  "internal",
  "timeout",
  "rate_limited",
  "upstream_unavailable"
]);
function newRequestId() {
  try {
    return crypto.randomUUID();
  } catch {
    return `req_${Date.now().toString(36)}`;
  }
}
function errorResult(message, errorCode = "internal") {
  return {
    content: [{ type: "text", text: message }],
    isError: true,
    structuredContent: {
      ok: false,
      contract: ERROR_CONTRACT_VERSION,
      error_code: errorCode,
      error: errorCode,
      message,
      retryable: RETRYABLE_CODES.has(errorCode),
      request_id: newRequestId(),
      finance_contract: FINANCE_CONTRACT_VERSION
    }
  };
}
function requireUser(ctx) {
  if (!ctx.isAuthenticated()) return null;
  return ctx.getUserId() ?? null;
}
function ok(text, structured) {
  return {
    content: [{ type: "text", text }],
    structuredContent: {
      ok: true,
      request_id: newRequestId(),
      finance_contract: FINANCE_CONTRACT_VERSION,
      ...structured ?? {}
    }
  };
}
function brl(value) {
  return `R$ ${Number(value ?? 0).toFixed(2).replace(".", ",")}`;
}
function currentMonth() {
  return (/* @__PURE__ */ new Date()).toISOString().slice(0, 7);
}

// src/lib/mcp/tools/list-transactions.ts
var list_transactions_default = defineTool({
  name: "list_transactions",
  title: "Listar lan\xE7amentos",
  description: "Lista os lan\xE7amentos financeiros (receitas e despesas) do usu\xE1rio autenticado, do mais recente para o mais antigo, com filtros opcionais de per\xEDodo e tipo.",
  inputSchema: {
    from: z.string().optional().describe("Data inicial em YYYY-MM-DD."),
    to: z.string().optional().describe("Data final em YYYY-MM-DD."),
    type: z.enum(["income", "expense", "transfer"]).optional().describe("Tipo do lan\xE7amento."),
    search: z.string().optional().describe("Texto para buscar na descri\xE7\xE3o."),
    limit: z.number().optional().describe("Quantidade m\xE1xima de lan\xE7amentos (padr\xE3o 50, m\xE1ximo 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, type, search, limit }, ctx) => {
    if (!requireUser(ctx)) return errorResult("N\xE3o autenticado.");
    const supabase = supabaseForUser(ctx);
    const max = Math.min(Math.max(Number(limit ?? 50), 1), 200);
    let query = supabase.from("transactions").select("id, occurred_at, description, friendly_description, amount, type, status, category_id, account_id").order("occurred_at", { ascending: false }).limit(max);
    if (from) query = query.gte("occurred_at", from);
    if (to) query = query.lte("occurred_at", to);
    if (type) query = query.eq("type", type);
    if (search) query = query.ilike("description", `%${search}%`);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    const rows = (data ?? []).map((t) => ({
      id: t.id,
      date: t.occurred_at,
      description: t.friendly_description || t.description || "(sem descri\xE7\xE3o)",
      amount: Number(t.amount),
      type: t.type,
      status: t.status
    }));
    if (rows.length === 0) return ok("Nenhum lan\xE7amento encontrado para esse filtro.", { transactions: [] });
    const text = rows.map((r) => `${r.date} \xB7 ${r.type === "income" ? "+" : "-"}${brl(Math.abs(r.amount))} \xB7 ${r.description}`).join("\n");
    return ok(text, { transactions: rows });
  }
});

// src/lib/mcp/tools/monthly-summary.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var TX_COLUMNS = "id,account_id,category_id,type,status,amount,refund_of_transaction_id,merchant_name,friendly_description,occurred_at,description,transfer_group_id,payment_method,credit_card_id,competence_date,settles_card_id,movement_kind";
var monthly_summary_default = defineTool2({
  name: "monthly_summary",
  title: "Resumo do m\xEAs",
  description: "Resume o m\xEAs do usu\xE1rio autenticado: total de receitas, total de despesas, saldo do per\xEDodo e as maiores categorias de gasto (regra comportamental \xFAnica do Meu Nino).",
  inputSchema: {
    month: z2.string().optional().describe("M\xEAs no formato YYYY-MM. Padr\xE3o: m\xEAs atual.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ month }, ctx) => {
    if (!requireUser(ctx)) return errorResult("N\xE3o autenticado.", "unauthorized");
    const supabase = supabaseForUser(ctx);
    const target = month && /^\d{4}-\d{2}$/.test(month) ? month : currentMonth();
    const [txRes, catRes, accRes, snapRes] = await Promise.all([
      supabase.from("transactions").select(TX_COLUMNS),
      supabase.from("categories").select("id, name, type"),
      supabase.from("accounts").select("id,name,type,opening_balance,active"),
      supabase.from("account_balance_snapshots").select("account_id,balance,balance_date,status,anchor_kind,source_document_id,reconciliation_delta")
    ]);
    if (txRes.error) return errorResult(txRes.error.message, "internal");
    const txs = (txRes.data ?? []).map((t) => ({
      id: String(t.id),
      account_id: String(t.account_id ?? ""),
      category_id: t.category_id ?? null,
      refund_of_transaction_id: t.refund_of_transaction_id ?? null,
      type: t.type,
      status: t.status,
      amount: Number(t.amount ?? 0),
      occurred_at: String(t.occurred_at ?? ""),
      description: t.description ?? null,
      transfer_group_id: t.transfer_group_id ?? null,
      payment_method: t.payment_method ?? null,
      credit_card_id: t.credit_card_id ?? null,
      competence_date: t.competence_date ?? null,
      settles_card_id: t.settles_card_id ?? null,
      movement_kind: t.movement_kind ?? "transaction"
    }));
    const categories = (catRes.data ?? []).map((c) => ({
      id: String(c.id),
      name: String(c.name ?? ""),
      type: c.type ?? "expense"
    }));
    const accounts = (accRes.data ?? []).map((a) => ({
      id: String(a.id),
      name: String(a.name ?? ""),
      type: String(a.type ?? "checking"),
      opening_balance: Number(a.opening_balance ?? 0),
      active: Boolean(a.active ?? true)
    }));
    const snapshots = (snapRes.data ?? []).map((s2) => ({
      account_id: String(s2.account_id ?? ""),
      balance: Number(s2.balance ?? 0),
      balance_date: String(s2.balance_date ?? ""),
      status: String(s2.status ?? "confirmed")
    }));
    const lastDay = new Date(Date.UTC(Number(target.slice(0, 4)), Number(target.slice(5, 7)), 0)).getUTCDate();
    const period = { start: `${target}-01`, end: `${target}-${String(lastDay).padStart(2, "0")}` };
    const bridge = computeCashBridge({ accounts, txs, snapshots, period });
    const performance = computePeriodPerformance(txs, period);
    const explanation = explainBalanceChange(bridge, performance);
    const totals = computeMonthlyTotals(txs, target);
    const breakdown = computeCategoryBreakdown(txs, categories, target, "expense");
    const top = breakdown.slice(0, 5);
    const lines = [
      `Resumo de ${target}`,
      `Receitas: ${brl(totals.income)}`,
      `Despesas: ${brl(totals.expense)}`,
      `Saldo do per\xEDodo: ${brl(totals.net)}`,
      top.length ? "\nMaiores gastos por categoria:" : "\nNenhuma despesa registrada no per\xEDodo.",
      ...top.map((c) => `- ${c.name}: ${brl(c.amount)}`),
      "",
      "Como o saldo se formou (ponte de caixa):",
      `Saldo inicial: ${brl(bridge.openingCash)} \u2192 Saldo final: ${brl(bridge.confirmedClosingCash)}`,
      explanation.headline,
      ...explanation.steps.map((l) => `- ${l}`),
      Math.abs(bridge.reconciliationDifference) > 0.01 ? `Aten\xE7\xE3o: reconcilia\xE7\xE3o pendente de ${brl(bridge.reconciliationDifference)} \u2014 n\xE3o afirme o saldo como exato.` : "Ponte reconciliada (diferen\xE7a \u2264 R$ 0,01)."
    ];
    return ok(lines.join("\n"), {
      month: target,
      income: totals.income,
      expense: totals.expense,
      balance: totals.net,
      top_categories: top.map((c) => ({ name: c.name, total: c.amount, share: c.share })),
      cash_bridge: {
        opening_cash: bridge.openingCash,
        closing_cash: bridge.confirmedClosingCash,
        operational_income: bridge.operationalIncome,
        operational_account_expense: bridge.operationalAccountExpense,
        investment_redemptions: bridge.investmentRedemptions,
        investment_applications: bridge.investmentApplications,
        card_payments: bridge.cardPayments,
        loan_proceeds: bridge.loanProceeds,
        debt_principal_payments: bridge.debtPrincipalPayments,
        external_transfers_in: bridge.externalTransfersIn,
        external_transfers_out: bridge.externalTransfersOut,
        refunds_and_reimbursements: bridge.refundsAndReimbursements,
        adjustments: bridge.adjustments,
        reconciliation_difference: bridge.reconciliationDifference,
        confidence: bridge.confidence
      },
      period_performance: {
        operational_income: performance.operationalIncome,
        operational_expense: performance.operationalExpense,
        operational_result: performance.operationalResult,
        operational_gap: performance.operationalGap,
        savings_rate: performance.savingsRate
      },
      balance_explanation: { headline: explanation.headline, body: explanation.body, steps: explanation.steps },
      formula_version: FINANCE_CONTRACT_VERSION
    });
  }
});

// src/lib/mcp/tools/list-accounts-and-categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_accounts_and_categories_default = defineTool3({
  name: "list_accounts_and_categories",
  title: "Listar contas e categorias",
  description: "Lista as contas ativas e as categorias do usu\xE1rio autenticado, com seus identificadores. Use antes de registrar um lan\xE7amento para escolher conta e categoria.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!requireUser(ctx)) return errorResult("N\xE3o autenticado.");
    const supabase = supabaseForUser(ctx);
    const [accRes, catRes] = await Promise.all([
      supabase.from("accounts").select("id, name, institution, type, opening_balance, active").eq("active", true),
      supabase.from("categories").select("id, name, type, archived_at").is("archived_at", null)
    ]);
    if (accRes.error) return errorResult(accRes.error.message);
    if (catRes.error) return errorResult(catRes.error.message);
    const accounts = (accRes.data ?? []).map((a) => ({
      id: a.id,
      name: a.name,
      institution: a.institution,
      type: a.type
    }));
    const categories = (catRes.data ?? []).map((c) => ({ id: c.id, name: c.name, type: c.type }));
    const text = [
      accounts.length ? "Contas:" : "Nenhuma conta cadastrada.",
      ...accounts.map((a) => `- ${a.name}${a.institution ? ` (${a.institution})` : ""} \xB7 ${a.id}`),
      "",
      categories.length ? "Categorias:" : "Nenhuma categoria cadastrada.",
      ...categories.map((c) => `- ${c.name} [${c.type}] \xB7 ${c.id}`)
    ].join("\n");
    return ok(text, { accounts, categories });
  }
});

// src/lib/mcp/tools/create-transaction.ts
import { defineTool as defineTool4, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var create_transaction_default = defineTool4({
  name: "create_transaction",
  title: "Registrar lan\xE7amento",
  description: "Registra uma despesa ou receita confirmada na conta do usu\xE1rio autenticado. Informe conta por nome ou identificador. S\xF3 envie category quando o usu\xE1rio tiver indicado explicitamente uma categoria; esse valor ser\xE1 tratado como hint e revalidado pelo Category Truth V2.",
  inputSchema: {
    amount: z3.number().describe("Valor positivo do lan\xE7amento."),
    description: z3.string().describe("Descri\xE7\xE3o do lan\xE7amento."),
    type: z3.enum(["expense", "income"]).describe("Tipo do lan\xE7amento."),
    occurred_at: z3.string().optional().describe("Data em YYYY-MM-DD. Padr\xE3o: hoje."),
    account: z3.string().optional().describe("Nome ou identificador da conta."),
    category: z3.string().optional().describe("Categoria explicitamente informada pelo usu\xE1rio; ser\xE1 revalidada pelo motor central.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ amount, description, type, occurred_at, account, category }, ctx) => {
    const userId = requireUser(ctx);
    if (!userId) return errorResult("N\xE3o autenticado.");
    if (!(amount > 0)) throw new ToolError("O valor precisa ser maior que zero.");
    const date = occurred_at && /^\d{4}-\d{2}-\d{2}$/.test(occurred_at) ? occurred_at : (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const supabase = supabaseForUser(ctx);
    const { data: accounts, error: accErr } = await supabase.from("accounts").select("id, name").eq("active", true);
    if (accErr) return errorResult(accErr.message);
    if (!accounts || accounts.length === 0) {
      return errorResult("Voc\xEA ainda n\xE3o tem contas cadastradas no Meu Nino. Crie uma conta no app antes de registrar lan\xE7amentos.");
    }
    const needle = (account ?? "").trim().toLowerCase();
    const chosen = needle ? accounts.find((a) => a.id === account) ?? accounts.find((a) => String(a.name).toLowerCase() === needle) ?? accounts.find((a) => String(a.name).toLowerCase().includes(needle)) : accounts.length === 1 ? accounts[0] : void 0;
    if (!chosen) {
      return errorResult(`N\xE3o identifiquei a conta. Op\xE7\xF5es: ${accounts.map((a) => a.name).join(", ")}.`);
    }
    let categoryId = null;
    if (category) {
      const { data: cats, error: catErr } = await supabase.from("categories").select("id, name, type").is("archived_at", null).eq("type", type);
      if (catErr) return errorResult(catErr.message);
      const cn = category.trim().toLowerCase();
      const match = (cats ?? []).find((c) => c.id === category) ?? (cats ?? []).find((c) => String(c.name).toLowerCase() === cn) ?? (cats ?? []).find((c) => String(c.name).toLowerCase().includes(cn));
      if (!match) return errorResult(`A categoria \u201C${category}\u201D n\xE3o \xE9 v\xE1lida para ${type === "expense" ? "despesa" : "receita"}.`);
      categoryId = match.id;
    }
    const { data, error } = await supabase.from("transactions").insert({
      user_id: userId,
      account_id: chosen.id,
      category_id: categoryId,
      category_source: categoryId ? "document_hint" : null,
      category_confidence: categoryId ? 0.6 : null,
      category_reason: categoryId ? "categoria recebida pelo MCP; aguardando valida\xE7\xE3o do motor central" : null,
      category_review_status: categoryId ? "needs_review" : void 0,
      type,
      status: "confirmed",
      amount,
      occurred_at: date,
      description: description.trim(),
      origin: "agent"
    }).select("id, occurred_at, amount, type, description, category_id, category_review_status").single();
    if (error) return errorResult(error.message);
    return ok(
      `Lan\xE7amento registrado: ${type === "income" ? "receita" : "despesa"} de ${brl(amount)} em ${date} \xB7 ${description} (conta ${chosen.name}).${categoryId ? " A categoria ser\xE1 validada pelo Nino." : ""}`,
      { transaction: data }
    );
  }
});

// src/lib/mcp/tools/financial-position.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var CARD_TX_PAGE_SIZE = 1e3;
var financial_position_default = defineTool5({
  name: "financial_position",
  title: "Posi\xE7\xE3o financeira",
  description: "Mostra a posi\xE7\xE3o financeira reconciliada do usu\xE1rio autenticado: cart\xF5es com obriga\xE7\xE3o atual (inclusive cart\xF5es inativos), parcelas futuras, d\xEDvidas fora do cart\xE3o e metas em andamento.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!requireUser(ctx)) return errorResult("N\xE3o autenticado.");
    const supabase = supabaseForUser(ctx);
    const [cardsRes, debtsRes, goalsRes, statementsRes, installmentsRes] = await Promise.all([
      supabase.from("credit_cards").select("id, name, brand, last_four, total_limit, closing_day, due_day, active"),
      supabase.from("debts").select("id, name, creditor, outstanding_balance, installment_amount, status"),
      supabase.from("goals").select("id, name, target_amount, target_date, status"),
      supabase.from("credit_card_statements").select("credit_card_id,competence_month,stated_total,paid_amount,outstanding_amount,reconciliation_difference,status"),
      supabase.from("credit_card_installments").select("credit_card_id,competence_month,amount,status,absorbed_by_statement_id")
    ]);
    const sourceResults = [
      ["cart\xF5es", cardsRes],
      ["d\xEDvidas", debtsRes],
      ["metas", goalsRes],
      ["faturas", statementsRes],
      ["parcelas", installmentsRes]
    ];
    for (const [source, result] of sourceResults) {
      if (result.error) {
        return errorResult(`N\xE3o foi poss\xEDvel reconciliar ${source} agora. Tente novamente.`, "upstream_unavailable");
      }
    }
    const txs = [];
    for (let from = 0; ; from += CARD_TX_PAGE_SIZE) {
      const page = await supabase.from("transactions").select("credit_card_id,competence_date,occurred_at,amount,type,status,settles_card_id").not("credit_card_id", "is", null).order("occurred_at", { ascending: true }).order("id", { ascending: true }).range(from, from + CARD_TX_PAGE_SIZE - 1);
      if (page.error) {
        return errorResult("N\xE3o foi poss\xEDvel reconciliar os lan\xE7amentos de cart\xE3o agora. Tente novamente.", "upstream_unavailable");
      }
      const rows = page.data ?? [];
      txs.push(...rows);
      if (rows.length < CARD_TX_PAGE_SIZE) break;
    }
    const exposures = computeCardExposure({
      cardIds: (cardsRes.data ?? []).map((c) => c.id),
      cards: (cardsRes.data ?? []).map((c) => ({
        id: c.id,
        closing_day: c.closing_day,
        due_day: c.due_day
      })),
      statements: statementsRes.data ?? [],
      installments: installmentsRes.data ?? [],
      txs,
      currentYM: currentMonthYM(),
      todayISO: todaySP()
    });
    const cardDebtToday = totalCardDebtOf(exposures);
    const cardFutureInstallments = totalFutureInstallmentsOf(exposures);
    const cards = (cardsRes.data ?? []).map((c) => {
      const e = exposures[c.id];
      return {
        id: c.id,
        name: c.name,
        brand: c.brand,
        last_four: c.last_four,
        active: c.active,
        limit: Number(c.total_limit ?? 0),
        due_day: c.due_day,
        current_statement: e?.currentStatement.amount ?? 0,
        current_statement_source: e?.currentStatement.source ?? "none",
        next_statement: e?.nextStatement.amount ?? 0,
        future_installments: e?.futureInstallments ?? 0,
        debt_today: e?.totalCardDebt ?? 0
      };
    });
    const debts = (debtsRes.data ?? []).filter((d) => d.status !== "settled");
    const goals = (goalsRes.data ?? []).filter((g) => g.status === "active");
    const lines = [
      cards.length ? "Cart\xF5es com posi\xE7\xE3o financeira:" : "Nenhuma obriga\xE7\xE3o de cart\xE3o encontrada.",
      ...cards.map(
        (c) => `- ${c.name} ${c.last_four ? `\u2022\u2022${c.last_four}` : ""} \xB7 limite ${brl(c.limit)} \xB7 fatura atual ${brl(c.current_statement)}${c.current_statement_source === "estimated" ? " (estimada)" : " (oficial)"} \xB7 d\xEDvida hoje ${brl(c.debt_today)}${c.active ? "" : " \xB7 cart\xE3o inativo, obriga\xE7\xE3o preservada"}`
      ),
      cards.length ? `D\xEDvida do cart\xE3o hoje: ${brl(cardDebtToday)} \xB7 compromisso futuro de parcelas (n\xE3o \xE9 d\xEDvida): ${brl(cardFutureInstallments)}` : "",
      "",
      debts.length ? "D\xEDvidas em aberto:" : "Nenhuma d\xEDvida em aberto.",
      ...debts.map((d) => `- ${d.name}${d.creditor ? ` (${d.creditor})` : ""} \xB7 saldo ${brl(Number(d.outstanding_balance ?? 0))}`),
      "",
      goals.length ? "Metas ativas:" : "Nenhuma meta ativa.",
      ...goals.map((g) => `- ${g.name} \xB7 objetivo ${brl(Number(g.target_amount ?? 0))}${g.target_date ? ` at\xE9 ${g.target_date}` : ""}`)
    ].filter(Boolean);
    return ok(lines.join("\n"), {
      cards,
      card_debt_today: cardDebtToday,
      card_future_installments: cardFutureInstallments,
      formula_version: "financial_position.v2",
      debts: debts.map((d) => ({ id: d.id, name: d.name, outstanding_balance: Number(d.outstanding_balance ?? 0) })),
      goals: goals.map((g) => ({ id: g.id, name: g.name, target_amount: Number(g.target_amount ?? 0), target_date: g.target_date }))
    });
  }
});

// src/lib/mcp/tools/list-card-statements.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_card_statements_default = defineTool6({
  name: "list_card_statements",
  title: "Listar faturas de cart\xE3o",
  description: "Lista faturas conciliadas do usu\xE1rio, com cart\xE3o, vencimento, total, valor pago, saldo e status.",
  inputSchema: {
    status: z4.enum(["open", "partially_paid", "paid", "overdue", "needs_review"]).optional(),
    limit: z4.number().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!requireUser(ctx)) return errorResult("N\xE3o autenticado.");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("credit_card_statements").select("id,credit_card_id,competence_month,due_date,stated_total,paid_amount,outstanding_amount,reconciliation_difference,status,credit_cards(name,last_four)").order("competence_month", { ascending: false }).limit(limit ?? 24);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    const statements = (data ?? []).map((row) => ({
      id: row.id,
      card: row.credit_cards?.name ?? "Cart\xE3o",
      last_four: row.credit_cards?.last_four ?? null,
      competence_month: row.competence_month,
      due_date: row.due_date,
      total: Number(row.stated_total),
      paid: Number(row.paid_amount),
      outstanding: Number(row.outstanding_amount),
      status: row.status,
      reconciled: Math.abs(Number(row.reconciliation_difference)) <= 0.05
    }));
    return ok(statements.length ? statements.map(
      (s) => `${s.card} \xB7 ${String(s.competence_month).slice(0, 7)} \xB7 ${brl(s.total)} \xB7 ${s.status} \xB7 falta ${brl(s.outstanding)}`
    ).join("\n") : "Nenhuma fatura encontrada.", { statements });
  }
});

// src/lib/mcp/tools/settle-card-statement.ts
import { defineTool as defineTool7, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var settle_card_statement_default = defineTool7({
  name: "settle_card_statement",
  title: "Registrar pagamento de fatura",
  description: "Registra a baixa cont\xE1bil de uma fatura ap\xF3s confirma\xE7\xE3o expl\xEDcita do usu\xE1rio. Reduz caixa e obriga\xE7\xE3o; n\xE3o cria uma nova despesa de consumo.",
  inputSchema: {
    statement_id: z5.string().uuid().describe("Identificador retornado por list_card_statements."),
    account_id: z5.string().uuid().describe("Conta usada no pagamento."),
    amount: z5.number().positive().optional().describe("Valor pago. Se omitido, quita o saldo em aberto."),
    paid_at: z5.string().optional().describe("Data YYYY-MM-DD."),
    confirmed_by_user: z5.literal(true).describe("S\xF3 use true ap\xF3s o usu\xE1rio confirmar claramente valor, conta e data."),
    idempotency_key: z5.string().min(8).describe("Chave \xFAnica e est\xE1vel para impedir pagamento duplicado em retries.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ statement_id, account_id, amount, paid_at, confirmed_by_user, idempotency_key }, ctx) => {
    if (!requireUser(ctx)) return errorResult("N\xE3o autenticado.");
    if (confirmed_by_user !== true) throw new ToolError2("Confirma\xE7\xE3o expl\xEDcita obrigat\xF3ria.");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("settle_credit_card_statement", {
      p_statement_id: statement_id,
      p_account_id: account_id,
      p_amount: amount ?? null,
      p_paid_at: paid_at ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
      p_idempotency_key: idempotency_key
    });
    if (error) return errorResult(error.message);
    const result = data;
    return ok(`Pagamento registrado: ${brl(Number(result.amount ?? amount ?? 0))}. Fatura ${result.status === "paid" ? "quitada" : "parcialmente paga"}.`, { payment: result });
  }
});

// src/lib/mcp/index.ts
var projectRef = "wesjjdjmlnfjihkkgzfp";
var mcp_default = defineMcp({
  name: "meu-nino",
  title: "Meu Nino",
  version: "0.1.0",
  instructions: "Ferramentas do Meu Nino, app de finan\xE7as pessoais em portugu\xEAs. Consulte lan\xE7amentos, resumo do m\xEAs, contas, categorias, cart\xF5es, faturas, d\xEDvidas e metas. Pagamento de fatura exige confirma\xE7\xE3o expl\xEDcita e \xE9 baixa de caixa/obriga\xE7\xE3o, nunca nova despesa de consumo. Valores em reais (BRL).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_transactions_default,
    monthly_summary_default,
    list_accounts_and_categories_default,
    create_transaction_default,
    financial_position_default,
    list_card_statements_default,
    settle_card_statement_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
