// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-transactions.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.6";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (ou VITE_SUPABASE_URL) \xE9 obrigat\xF3rio");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS ou SUPABASE_ANON_KEY \xE9 obrigat\xF3rio");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser exige um token OAuth verificado");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/shared.ts
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function requireUser(ctx) {
  if (!ctx.isAuthenticated()) return null;
  return ctx.getUserId() ?? null;
}
function ok(text, structured) {
  return { content: [{ type: "text", text }], structuredContent: structured };
}
function brl(value) {
  return `R$ ${Number(value ?? 0).toFixed(2).replace(".", ",")}`;
}
function monthRange(month) {
  const [y, m] = month.split("-").map(Number);
  const start = new Date(Date.UTC(y, m - 1, 1));
  const end = new Date(Date.UTC(y, m, 0));
  return { from: start.toISOString().slice(0, 10), to: end.toISOString().slice(0, 10) };
}
function currentMonth() {
  return (/* @__PURE__ */ new Date()).toISOString().slice(0, 7);
}

// src/lib/mcp/tools/list-transactions.ts
var list_transactions_default = defineTool({
  name: "list_transactions",
  title: "Listar lan\xE7amentos",
  description: "Lista os lan\xE7amentos financeiros (receitas e despesas) do usu\xE1rio autenticado, do mais recente para o mais antigo, com filtros opcionais de per\xEDodo e tipo.",
  inputSchema: {
    from: z.string().optional().describe("Data inicial em YYYY-MM-DD."),
    to: z.string().optional().describe("Data final em YYYY-MM-DD."),
    type: z.enum(["income", "expense", "transfer"]).optional().describe("Tipo do lan\xE7amento."),
    search: z.string().optional().describe("Texto para buscar na descri\xE7\xE3o."),
    limit: z.number().optional().describe("Quantidade m\xE1xima de lan\xE7amentos (padr\xE3o 50, m\xE1ximo 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, type, search, limit }, ctx) => {
    if (!requireUser(ctx)) return errorResult("N\xE3o autenticado.");
    const supabase = supabaseForUser(ctx);
    const max = Math.min(Math.max(Number(limit ?? 50), 1), 200);
    let query = supabase.from("transactions").select("id, occurred_at, description, friendly_description, amount, type, status, category_id, account_id").order("occurred_at", { ascending: false }).limit(max);
    if (from) query = query.gte("occurred_at", from);
    if (to) query = query.lte("occurred_at", to);
    if (type) query = query.eq("type", type);
    if (search) query = query.ilike("description", `%${search}%`);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    const rows = (data ?? []).map((t) => ({
      id: t.id,
      date: t.occurred_at,
      description: t.friendly_description || t.description || "(sem descri\xE7\xE3o)",
      amount: Number(t.amount),
      type: t.type,
      status: t.status
    }));
    if (rows.length === 0) return ok("Nenhum lan\xE7amento encontrado para esse filtro.", { transactions: [] });
    const text = rows.map((r) => `${r.date} \xB7 ${r.type === "income" ? "+" : "-"}${brl(Math.abs(r.amount))} \xB7 ${r.description}`).join("\n");
    return ok(text, { transactions: rows });
  }
});

// src/lib/mcp/tools/monthly-summary.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var monthly_summary_default = defineTool2({
  name: "monthly_summary",
  title: "Resumo do m\xEAs",
  description: "Resume o m\xEAs do usu\xE1rio autenticado: total de receitas, total de despesas, saldo do per\xEDodo e as maiores categorias de gasto.",
  inputSchema: {
    month: z2.string().optional().describe("M\xEAs no formato YYYY-MM. Padr\xE3o: m\xEAs atual.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ month }, ctx) => {
    if (!requireUser(ctx)) return errorResult("N\xE3o autenticado.");
    const supabase = supabaseForUser(ctx);
    const target = month && /^\d{4}-\d{2}$/.test(month) ? month : currentMonth();
    const { from, to } = monthRange(target);
    const [txRes, catRes] = await Promise.all([
      supabase.from("transactions").select("amount, type, category_id").gte("occurred_at", from).lte("occurred_at", to).eq("status", "confirmed"),
      supabase.from("categories").select("id, name")
    ]);
    if (txRes.error) return errorResult(txRes.error.message);
    const catNames = new Map((catRes.data ?? []).map((c) => [c.id, c.name]));
    let income = 0;
    let expense = 0;
    const byCategory = /* @__PURE__ */ new Map();
    for (const t of txRes.data ?? []) {
      const value = Math.abs(Number(t.amount));
      if (t.type === "income") income += value;
      else if (t.type === "expense") {
        expense += value;
        const label = catNames.get(t.category_id) ?? "Sem categoria";
        byCategory.set(label, (byCategory.get(label) ?? 0) + value);
      }
    }
    const top = [...byCategory.entries()].sort((a, b) => b[1] - a[1]).slice(0, 5);
    const lines = [
      `Resumo de ${target}`,
      `Receitas: ${brl(income)}`,
      `Despesas: ${brl(expense)}`,
      `Saldo do per\xEDodo: ${brl(income - expense)}`,
      top.length ? "\nMaiores gastos por categoria:" : "\nNenhuma despesa registrada no per\xEDodo.",
      ...top.map(([name, value]) => `- ${name}: ${brl(value)}`)
    ];
    return ok(lines.join("\n"), {
      month: target,
      income,
      expense,
      balance: income - expense,
      top_categories: top.map(([name, value]) => ({ name, total: value }))
    });
  }
});

// src/lib/mcp/tools/list-accounts-and-categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_accounts_and_categories_default = defineTool3({
  name: "list_accounts_and_categories",
  title: "Listar contas e categorias",
  description: "Lista as contas ativas e as categorias do usu\xE1rio autenticado, com seus identificadores. Use antes de registrar um lan\xE7amento para escolher conta e categoria.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!requireUser(ctx)) return errorResult("N\xE3o autenticado.");
    const supabase = supabaseForUser(ctx);
    const [accRes, catRes] = await Promise.all([
      supabase.from("accounts").select("id, name, institution, type, opening_balance, active").eq("active", true),
      supabase.from("categories").select("id, name, type, archived_at").is("archived_at", null)
    ]);
    if (accRes.error) return errorResult(accRes.error.message);
    if (catRes.error) return errorResult(catRes.error.message);
    const accounts = (accRes.data ?? []).map((a) => ({
      id: a.id,
      name: a.name,
      institution: a.institution,
      type: a.type
    }));
    const categories = (catRes.data ?? []).map((c) => ({ id: c.id, name: c.name, type: c.type }));
    const text = [
      accounts.length ? "Contas:" : "Nenhuma conta cadastrada.",
      ...accounts.map((a) => `- ${a.name}${a.institution ? ` (${a.institution})` : ""} \xB7 ${a.id}`),
      "",
      categories.length ? "Categorias:" : "Nenhuma categoria cadastrada.",
      ...categories.map((c) => `- ${c.name} [${c.type}] \xB7 ${c.id}`)
    ].join("\n");
    return ok(text, { accounts, categories });
  }
});

// src/lib/mcp/tools/create-transaction.ts
import { defineTool as defineTool4, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var create_transaction_default = defineTool4({
  name: "create_transaction",
  title: "Registrar lan\xE7amento",
  description: "Registra uma despesa ou receita confirmada na conta do usu\xE1rio autenticado. Informe conta e categoria por nome ou identificador; quando o usu\xE1rio tem apenas uma conta, ela \xE9 usada automaticamente.",
  inputSchema: {
    amount: z3.number().describe("Valor positivo do lan\xE7amento."),
    description: z3.string().describe("Descri\xE7\xE3o do lan\xE7amento."),
    type: z3.enum(["expense", "income"]).describe("Tipo do lan\xE7amento."),
    occurred_at: z3.string().optional().describe("Data em YYYY-MM-DD. Padr\xE3o: hoje."),
    account: z3.string().optional().describe("Nome ou identificador da conta."),
    category: z3.string().optional().describe("Nome ou identificador da categoria.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ amount, description, type, occurred_at, account, category }, ctx) => {
    const userId = requireUser(ctx);
    if (!userId) return errorResult("N\xE3o autenticado.");
    if (!(amount > 0)) throw new ToolError("O valor precisa ser maior que zero.");
    const date = occurred_at && /^\d{4}-\d{2}-\d{2}$/.test(occurred_at) ? occurred_at : (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const supabase = supabaseForUser(ctx);
    const { data: accounts, error: accErr } = await supabase.from("accounts").select("id, name").eq("active", true);
    if (accErr) return errorResult(accErr.message);
    if (!accounts || accounts.length === 0) {
      return errorResult("Voc\xEA ainda n\xE3o tem contas cadastradas no Meu Nino. Crie uma conta no app antes de registrar lan\xE7amentos.");
    }
    const needle = (account ?? "").trim().toLowerCase();
    const chosen = needle ? accounts.find((a) => a.id === account) ?? accounts.find((a) => String(a.name).toLowerCase() === needle) ?? accounts.find((a) => String(a.name).toLowerCase().includes(needle)) : accounts.length === 1 ? accounts[0] : void 0;
    if (!chosen) {
      return errorResult(
        `N\xE3o identifiquei a conta. Op\xE7\xF5es: ${accounts.map((a) => a.name).join(", ")}.`
      );
    }
    let categoryId = null;
    if (category) {
      const { data: cats } = await supabase.from("categories").select("id, name, type").is("archived_at", null);
      const cn = category.trim().toLowerCase();
      const match = (cats ?? []).find((c) => c.id === category) ?? (cats ?? []).find((c) => String(c.name).toLowerCase() === cn) ?? (cats ?? []).find((c) => String(c.name).toLowerCase().includes(cn));
      categoryId = match?.id ?? null;
    }
    const { data, error } = await supabase.from("transactions").insert({
      user_id: userId,
      account_id: chosen.id,
      category_id: categoryId,
      type,
      status: "confirmed",
      amount,
      occurred_at: date,
      description: description.trim(),
      origin: "agent"
    }).select("id, occurred_at, amount, type, description").single();
    if (error) return errorResult(error.message);
    return ok(
      `Lan\xE7amento registrado: ${type === "income" ? "receita" : "despesa"} de ${brl(amount)} em ${date} \xB7 ${description} (conta ${chosen.name}).`,
      { transaction: data }
    );
  }
});

// src/lib/mcp/tools/financial-position.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var financial_position_default = defineTool5({
  name: "financial_position",
  title: "Posi\xE7\xE3o financeira",
  description: "Mostra a posi\xE7\xE3o atual do usu\xE1rio autenticado: cart\xF5es de cr\xE9dito ativos, d\xEDvidas em aberto e metas em andamento.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!requireUser(ctx)) return errorResult("N\xE3o autenticado.");
    const supabase = supabaseForUser(ctx);
    const [cardsRes, debtsRes, goalsRes] = await Promise.all([
      supabase.from("credit_cards").select("id, name, brand, last_four, total_limit, due_day").eq("active", true),
      supabase.from("debts").select("id, name, creditor, outstanding_balance, installment_amount, status"),
      supabase.from("goals").select("id, name, target_amount, target_date, status")
    ]);
    if (cardsRes.error) return errorResult(cardsRes.error.message);
    const cards = (cardsRes.data ?? []).map((c) => ({
      id: c.id,
      name: c.name,
      brand: c.brand,
      last_four: c.last_four,
      limit: Number(c.total_limit ?? 0),
      due_day: c.due_day
    }));
    const debts = (debtsRes.data ?? []).filter((d) => d.status !== "settled");
    const goals = (goalsRes.data ?? []).filter((g) => g.status === "active");
    const lines = [
      cards.length ? "Cart\xF5es ativos:" : "Nenhum cart\xE3o ativo.",
      ...cards.map((c) => `- ${c.name} ${c.last_four ? `\u2022\u2022${c.last_four}` : ""} \xB7 limite ${brl(c.limit)} \xB7 vence dia ${c.due_day ?? "-"}`),
      "",
      debts.length ? "D\xEDvidas em aberto:" : "Nenhuma d\xEDvida em aberto.",
      ...debts.map((d) => `- ${d.name}${d.creditor ? ` (${d.creditor})` : ""} \xB7 saldo ${brl(Number(d.outstanding_balance ?? 0))}`),
      "",
      goals.length ? "Metas ativas:" : "Nenhuma meta ativa.",
      ...goals.map((g) => `- ${g.name} \xB7 objetivo ${brl(Number(g.target_amount ?? 0))}${g.target_date ? ` at\xE9 ${g.target_date}` : ""}`)
    ];
    return ok(lines.join("\n"), {
      cards,
      debts: debts.map((d) => ({ id: d.id, name: d.name, outstanding_balance: Number(d.outstanding_balance ?? 0) })),
      goals: goals.map((g) => ({ id: g.id, name: g.name, target_amount: Number(g.target_amount ?? 0), target_date: g.target_date }))
    });
  }
});

// src/lib/mcp/index.ts
var projectRef = "wesjjdjmlnfjihkkgzfp";
var mcp_default = defineMcp({
  name: "meu-nino",
  title: "Meu Nino",
  version: "0.1.0",
  instructions: "Ferramentas do Meu Nino, app de finan\xE7as pessoais em portugu\xEAs. Consulte lan\xE7amentos, resumo do m\xEAs, contas, categorias, cart\xF5es, d\xEDvidas e metas do usu\xE1rio conectado, e registre novos lan\xE7amentos. Valores em reais (BRL).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_transactions_default,
    monthly_summary_default,
    list_accounts_and_categories_default,
    create_transaction_default,
    financial_position_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
