begin;

alter table public.financial_situations
  add column if not exists narrative_role text not null default 'support',
  add column if not exists one_line_summary text;
alter table public.financial_situations drop constraint if exists financial_situations_narrative_role_check;
alter table public.financial_situations add constraint financial_situations_narrative_role_check check (narrative_role in ('primary','support','counterpoint','operational'));
create unique index if not exists financial_situations_user_mode_key_uidx on public.financial_situations(user_id,run_mode,situation_key);

alter table public.nino_diagnosis_config add column if not exists assembler_version text not null default 'v1_1';
alter table public.nino_diagnosis_config drop constraint if exists nino_diagnosis_config_assembler_version_check;
alter table public.nino_diagnosis_config add constraint nino_diagnosis_config_assembler_version_check check (assembler_version in ('v1','v1_1'));

create table public.financial_situation_events (
 id uuid primary key default gen_random_uuid(), user_id uuid not null,
 situation_id uuid not null references public.financial_situations(id) on delete cascade,
 event_type text not null check(event_type in ('detected','confirmed','worsened','improved','resolved','expired','superseded','acted','feedback')),
 from_status text,to_status text,delta_amount numeric,narrative text not null,
 metadata jsonb not null default '{}'::jsonb,occurred_at timestamptz not null default now()
);
grant select on public.financial_situation_events to authenticated;
grant all on public.financial_situation_events to service_role;
alter table public.financial_situation_events enable row level security;
create policy financial_situation_events_select_own on public.financial_situation_events for select to authenticated using(user_id=auth.uid());
create index financial_situation_events_timeline_idx on public.financial_situation_events(user_id,situation_id,occurred_at desc);
create unique index financial_situation_events_detected_uidx on public.financial_situation_events(situation_id,event_type) where event_type='detected';

create or replace function public.nino_diag_situation_event() returns trigger language plpgsql security definer set search_path=public as $$
declare v_type text; begin
 if tg_op='INSERT' then insert into public.financial_situation_events(user_id,situation_id,event_type,to_status,delta_amount,narrative) values(new.user_id,new.id,'detected',new.status,new.impact_amount,coalesce(new.one_line_summary,new.headline)) on conflict do nothing; return new; end if;
 if new.status is not distinct from old.status and new.severity is not distinct from old.severity and new.impact_amount is not distinct from old.impact_amount then return new; end if;
 v_type:=case when new.status='resolved' then 'resolved' when new.status='expired' then 'expired' when new.supersedes_id is not null and old.supersedes_id is null then 'superseded' when new.status='confirmed' and old.status<>'confirmed' then 'confirmed' when new.status='improving' or coalesce(new.impact_amount,0)<coalesce(old.impact_amount,0) then 'improved' else 'worsened' end;
 insert into public.financial_situation_events(user_id,situation_id,event_type,from_status,to_status,delta_amount,narrative,metadata) values(new.user_id,new.id,v_type,old.status,new.status,coalesce(new.impact_amount,0)-coalesce(old.impact_amount,0),case v_type when 'improved' then 'A situação melhorou desde a leitura anterior.' when 'resolved' then 'A situação foi resolvida.' when 'expired' then 'A janela desta situação terminou.' when 'confirmed' then 'A situação foi confirmada por novas evidências.' else 'A situação exige mais atenção do que na leitura anterior.' end,jsonb_build_object('from_severity',old.severity,'to_severity',new.severity)); return new;
end $$;
create trigger trg_nino_situation_event after insert or update on public.financial_situations for each row execute function public.nino_diag_situation_event();
insert into public.financial_situation_events(user_id,situation_id,event_type,to_status,delta_amount,narrative,occurred_at) select user_id,id,'detected',status,impact_amount,coalesce(one_line_summary,headline),created_at from public.financial_situations on conflict do nothing;

create or replace function public.nino_diag_select_action(_situation_type text,_status text,_evaluation jsonb default '{}'::jsonb,_impact numeric default null) returns jsonb language sql stable set search_path=public as $$
select case
 when _status in ('resolved','expired','suppressed') then '{}'::jsonb
 when _situation_type='behavioral_pattern' and _status='observed' then jsonb_build_object('key','understand_pattern','type','learn','title','Entender o padrão','route','/app/nino?section=aprendizados','explanation','Veja as evidências antes de tratar o padrão como confirmado','priority',55)
 when _situation_type='behavioral_pattern' then jsonb_build_object('key','review_pattern_spend','type','review','title','Ver os gastos do padrão','route','/app/lancamentos','explanation','Confira os lançamentos que sustentam este padrão','priority',60)
 when _situation_type='data_quality_issue' then jsonb_build_object('key','classify_transactions','type','classify','title','Classificar lançamentos','route','/app/lancamentos?filtro=sem-categoria','explanation','Melhorar a classificação aumenta a confiança das leituras','priority',85)
 when _situation_type='duplicate_review' then jsonb_build_object('key','review_duplicates','type','review','title','Revisar duplicidades','route','/app/lancamentos','explanation','Confirme quais lançamentos representam a mesma compra','priority',90)
 when _situation_type='goal_feasibility' then jsonb_build_object('key','recalibrate_goal','type','plan','title','Recalibrar meta','route',coalesce('/app/metas/'||nullif(_evaluation->>'goal_id',''),'/app/metas'),'explanation','Ajuste prazo ou aporte para tornar a meta viável','estimated_impact',_impact,'priority',80)
 when _situation_type='card_cycle_pressure' or _evaluation->>'future_kind' in ('bill','installment') then jsonb_build_object('key','review_card','type','review','title','Revisar fatura e parcelas','route',coalesce('/app/cartoes/'||nullif(_evaluation->>'card_id',''),'/app/cartoes'),'explanation','Antecipe o impacto antes do vencimento','estimated_impact',_impact,'priority',85)
 when _situation_type='cash_flow_imbalance' then jsonb_build_object('key','review_month_pressure','type','review','title','Ver o que pressionou o mês','route','/app/relatorios?foco=categorias&periodo=atual','explanation','Identifique as causas com maior impacto no caixa','estimated_impact',_impact,'priority',80)
 when _situation_type='anticipation' then jsonb_build_object('key','plan_ahead','type','plan','title','Planejar agora','route','/app/planejamento','explanation','Organize o caixa antes da data prevista','estimated_impact',_impact,'priority',80)
 when _situation_type='spending_pace_change' and _status='improving' then jsonb_build_object('key','review_improvement','type','review','title','Ver o que melhorou','route','/app/relatorios','explanation','Entenda o comportamento que ajudou o período','priority',45)
 else jsonb_build_object('key','review_details','type','review','title','Ver detalhes','route','/app/relatorios','explanation','Confira os fatos usados nesta leitura','estimated_impact',_impact,'priority',60) end $$;

create or replace function public.nino_diag_resolve_conflicts(_user_id uuid,_run_mode text default 'live') returns integer language plpgsql security definer set search_path=public as $$
declare v_count int; begin
 update public.financial_situations set narrative_role=case when situation_type in ('data_quality_issue','duplicate_review','shared_payment_confirmation') then 'operational' else 'support' end where user_id=_user_id and run_mode=_run_mode;
 with ranked as (select id,row_number() over(partition by situation_type order by relevance_score desc,updated_at desc) rn from public.financial_situations where user_id=_user_id and run_mode=_run_mode and status in ('active','confirmed','improving','worsening') and (severity='positive' or status='improving')) update public.financial_situations s set narrative_role='counterpoint' from ranked r where s.id=r.id and r.rn=1;
 get diagnostics v_count=row_count; return v_count; end $$;

create or replace function public.nino_evaluate_future_situations(_user_id uuid,_as_of date,_run_mode text,_run_id uuid) returns integer language plpgsql security definer set search_path=public as $$
declare r record; v_count int:=0; v_eval jsonb; v_action jsonb; begin
 for r in
  select 'bill' kind,s.id source_id,s.credit_card_id context_id,s.due_date event_date,greatest(s.outstanding_amount,0) amount,'Fatura vence em breve' headline from public.credit_card_statements s where s.user_id=_user_id and s.due_date between _as_of+1 and _as_of+15 and s.outstanding_amount>0
  union all select 'installment',(array_agg(i.id order by i.due_date))[1],i.credit_card_id,min(i.due_date),sum(i.amount),'Parcelas já comprometem os próximos dias' from public.credit_card_installments i where i.user_id=_user_id and i.due_date between _as_of+1 and _as_of+30 and i.status not in ('paid','cancelled') group by i.credit_card_id
  union all select 'recurring',(array_agg(o.id order by o.due_date))[1],null,min(o.due_date),sum(rr.amount),'Compromissos recorrentes estão próximos' from public.recurring_occurrences o join public.recurring_rules rr on rr.id=o.recurring_rule_id where o.user_id=_user_id and o.due_date between _as_of+1 and _as_of+15 and o.status='planned' group by o.user_id
  union all select 'debt',d.id,null,make_date(extract(year from _as_of)::int,extract(month from _as_of)::int,least(d.due_day,28)),d.installment_amount,'Parcela de dívida se aproxima' from public.debts d where d.user_id=_user_id and d.status='active' and d.installment_amount>0 and make_date(extract(year from _as_of)::int,extract(month from _as_of)::int,least(d.due_day,28)) between _as_of+1 and _as_of+15
  union all select 'goal',g.id,null,least(g.target_date,_as_of+30),greatest(g.target_amount-coalesce((select sum(c.amount) from public.goal_contributions c where c.goal_id=g.id),0),0),'Sua meta pede um próximo aporte' from public.goals g where g.user_id=_user_id and g.status='active' and g.target_date>=_as_of and g.target_amount>coalesce((select sum(c.amount) from public.goal_contributions c where c.goal_id=g.id),0)
 loop
  v_eval:=jsonb_build_object('future_kind',r.kind,'source_id',r.source_id,'card_id',r.context_id,'opportunity_date',r.event_date,'goal_id',case when r.kind='goal' then r.source_id else null end);
  v_action:=public.nino_diag_select_action(case when r.kind='goal' then 'goal_feasibility' else 'anticipation' end,'active',v_eval,r.amount);
  perform public.nino_diag_put_situation(_user_id,_run_mode,_run_id,_as_of,case when r.kind='goal' then 'goal_feasibility' else 'anticipation' end,'future:'||r.kind||':'||r.source_id::text,'active','future',case when r.amount>=1000 then 'attention' else 'info' end,.90,_as_of,r.event_date,r.amount,null,null,null,r.amount,r.headline,'Compromisso identificado nos seus dados financeiros.','Esse valor pode reduzir o caixa disponível na data prevista.','Data prevista: '||to_char(r.event_date,'DD/MM/YYYY'),r.event_date::timestamptz+interval '1 day',v_eval,jsonb_build_object('evidence_type','future_commitment','value',r.amount),v_action); v_count:=v_count+1;
 end loop;
 update public.financial_situations set status='expired',resolved_at=now(),updated_at=now() where user_id=_user_id and run_mode=_run_mode and temporal_scope='future' and valid_until<now() and status not in ('expired','resolved','suppressed'); return v_count; end $$;

create or replace function public.nino_assemble_diagnosis(_user_id uuid,_as_of date default current_date,_run_mode text default 'live') returns uuid language plpgsql security definer set search_path=public as $$
declare v_primary public.financial_situations; v_supporting uuid[]:='{}'; v_action uuid; v_state text:='stable'; v_conf numeric:=0; v_snapshot uuid; v_quality jsonb; v_payload jsonb; v_narrative jsonb; v_counter jsonb; v_max int:=3; v_min numeric:=.60; begin
 perform public.nino_diag_resolve_conflicts(_user_id,_run_mode); select max_supporting,min_primary_confidence into v_max,v_min from public.nino_diagnosis_config where singleton;
 select * into v_primary from public.financial_situations s where s.user_id=_user_id and s.run_mode=_run_mode and s.status in ('active','confirmed','improving','worsening') and s.temporal_scope in ('now','future') and s.situation_type not in ('data_quality_issue','duplicate_review','shared_payment_confirmation','behavioral_pattern') and s.confidence>=v_min and (s.valid_until is null or s.valid_until>now()) order by case s.severity when 'critical' then 4 when 'attention' then 3 when 'positive' then 2 else 1 end desc,s.relevance_score desc limit 1;
 if v_primary.id is not null then update public.financial_situations set narrative_role='primary',one_line_summary=coalesce(one_line_summary,headline) where id=v_primary.id; select id into v_action from public.financial_situation_actions where situation_id=v_primary.id and status in ('proposed','accepted','in_progress') order by priority desc limit 1; v_state:=case v_primary.severity when 'critical' then 'critical' when 'attention' then 'attention' when 'positive' then 'positive' else 'stable' end; v_conf:=v_primary.confidence; elsif not exists(select 1 from public.transactions where user_id=_user_id and status='confirmed') then v_state:='insufficient_data'; end if;
 select coalesce(array_agg(id order by role_order,relevance_score desc),'{}') into v_supporting from (select s.id,s.relevance_score,case s.narrative_role when 'counterpoint' then 1 else 2 end role_order from public.financial_situations s where s.user_id=_user_id and s.run_mode=_run_mode and s.id is distinct from v_primary.id and s.status in ('active','confirmed','improving','worsening') and s.temporal_scope in ('now','future') and s.situation_type not in ('data_quality_issue','duplicate_review','shared_payment_confirmation','behavioral_pattern') and (s.valid_until is null or s.valid_until>now()) order by role_order,relevance_score desc limit v_max) q;
 select to_jsonb(s) into v_counter from public.financial_situations s where s.id=any(v_supporting) and s.narrative_role='counterpoint' order by s.relevance_score desc limit 1;
 v_narrative:=jsonb_build_object('conclusion',v_primary.headline,'cause',v_primary.cause_summary,'counterpoint',v_counter->>'one_line_summary','consequence',v_primary.consequence_summary,'forecast',v_primary.forecast_summary,'action',(select to_jsonb(a) from public.financial_situation_actions a where a.id=v_action));
 v_quality:=jsonb_build_object('uncategorized_count',coalesce((select (evaluation->>'uncategorized_count')::int from public.financial_situations where user_id=_user_id and run_mode=_run_mode and situation_type='data_quality_issue' order by updated_at desc limit 1),0));
 v_payload:=jsonb_build_object('narrative',v_narrative,'primary_situation',(select to_jsonb(s) from public.financial_situations s where s.id=v_primary.id),'primary_action',(select to_jsonb(a) from public.financial_situation_actions a where a.id=v_action),'supporting_situations',coalesce((select jsonb_agg(to_jsonb(s) order by array_position(v_supporting,s.id)) from public.financial_situations s where s.id=any(v_supporting)),'[]'));
 if _run_mode='live' then update public.nino_diagnosis_snapshots set is_current=false where user_id=_user_id and run_mode='live' and is_current; end if;
 insert into public.nino_diagnosis_snapshots(user_id,run_mode,as_of,overall_state,primary_situation_id,supporting_situation_ids,primary_action_id,forecast,data_quality,confidence,rationale,payload,contract_version,is_current) values(_user_id,_run_mode,_as_of,v_state,v_primary.id,v_supporting,v_action,jsonb_build_object('summary',v_primary.forecast_summary),v_quality,v_conf,jsonb_build_object('primary_score',v_primary.relevance_score,'supporting_roles',(select coalesce(jsonb_object_agg(id,narrative_role),'{}') from public.financial_situations where id=any(v_supporting)),'conflict_resolution','counterpoints_preserved'),v_payload,'nino_diagnosis_contract.v1.1',_run_mode='live') returning id into v_snapshot; return v_snapshot; end $$;

create or replace function public.nino_refresh_diagnosis(_user_id uuid,_as_of date default current_date,_run_mode text default 'live',_source text default 'engine') returns jsonb language plpgsql security definer set search_path=public as $$
declare v_eval jsonb; v_snapshot uuid; v_projected int:=0; v_communications int:=0; v_future int:=0; begin v_eval:=public.nino_evaluate_financial_situations(_user_id,_as_of,_run_mode,_source); v_future:=public.nino_evaluate_future_situations(_user_id,_as_of,_run_mode,(v_eval->>'run_id')::uuid); v_snapshot:=public.nino_assemble_diagnosis(_user_id,_as_of,_run_mode); if _run_mode='live' then v_projected:=public.nino_project_diagnosis(_user_id,v_snapshot); v_communications:=public.nino_project_diagnosis_communications(_user_id,v_snapshot); end if; update public.nino_diagnosis_runs set projected_items=v_projected,finished_at=coalesce(finished_at,now()) where id=(v_eval->>'run_id')::uuid; return v_eval||jsonb_build_object('snapshot_id',v_snapshot,'projected_items',v_projected,'future_situations',v_future,'communications',v_communications); end $$;

create or replace function public.nino_diagnosis_context_for_user(_user_id uuid) returns jsonb language plpgsql stable security definer set search_path=public as $$
declare v public.nino_diagnosis_snapshots; begin if _user_id is null then return jsonb_build_object('ok',false,'error','missing_user'); end if; select * into v from public.nino_diagnosis_snapshots where user_id=_user_id and run_mode='live' and is_current order by created_at desc limit 1; if v.id is null then return jsonb_build_object('ok',true,'contract','nino_diagnosis_contract.v1.1','snapshot_id',null,'as_of',now(),'overall_state','insufficient_data','primary_situation',null,'primary_action',null,'supporting_situations','[]'::jsonb,'patterns','[]'::jsonb,'anticipations','[]'::jsonb,'operational_tasks','[]'::jsonb,'timeline','[]'::jsonb,'closings','[]'::jsonb,'narrative','{}'::jsonb,'forecast','{}'::jsonb,'data_quality','{}'::jsonb,'confidence',0,'rationale','{}'::jsonb,'snapshot_payload','{}'::jsonb); end if;
 return jsonb_build_object('ok',true,'contract',v.contract_version,'snapshot_id',v.id,'as_of',v.created_at,'overall_state',v.overall_state,'primary_situation',(select to_jsonb(s) from public.financial_situations s where s.id=v.primary_situation_id),'primary_action',(select to_jsonb(a) from public.financial_situation_actions a where a.id=v.primary_action_id),'supporting_situations',coalesce((select jsonb_agg(to_jsonb(s) order by array_position(v.supporting_situation_ids,s.id)) from public.financial_situations s where s.id=any(v.supporting_situation_ids)),'[]'::jsonb),'patterns',coalesce((select jsonb_agg(to_jsonb(s) order by relevance_score desc) from public.financial_situations s where user_id=_user_id and run_mode='live' and situation_type='behavioral_pattern' and status in ('observed','confirmed','active')),'[]'::jsonb),'anticipations',coalesce((select jsonb_agg(to_jsonb(s) order by period_end) from public.financial_situations s where user_id=_user_id and run_mode='live' and temporal_scope='future' and status in ('active','confirmed')),'[]'::jsonb),'operational_tasks',coalesce((select jsonb_agg(to_jsonb(s) order by relevance_score desc) from public.financial_situations s where user_id=_user_id and run_mode='live' and narrative_role='operational' and status in ('observed','active','confirmed')),'[]'::jsonb),'timeline',coalesce((select jsonb_agg(x order by x->>'last_event_at' desc) from (select jsonb_build_object('situation_id',s.id,'situation_key',s.situation_key,'headline',s.headline,'last_event_at',max(e.occurred_at),'events',jsonb_agg(to_jsonb(e) order by e.occurred_at desc)) x from public.financial_situations s join public.financial_situation_events e on e.situation_id=s.id where s.user_id=_user_id group by s.id order by max(e.occurred_at) desc limit 20) q),'[]'::jsonb),'closings',coalesce((select jsonb_agg(jsonb_build_object('id',id,'report_type',report_type,'period_start',period_start,'period_end',period_end,'summary',executive_summary,'closing_text',closing_text,'created_at',created_at) order by period_end desc) from public.financial_reports where user_id=_user_id and status in ('generated','published')),'[]'::jsonb),'narrative',coalesce(v.payload->'narrative','{}'::jsonb),'forecast',v.forecast,'data_quality',v.data_quality,'confidence',v.confidence,'rationale',v.rationale,'snapshot_payload',v.payload); end $$;

create or replace function public.my_nino_situation_feedback(_situation_id uuid,_feedback text,_surface text default 'nino') returns jsonb language plpgsql security definer set search_path=public as $$
declare v_uid uuid:=auth.uid(); begin if v_uid is null then return jsonb_build_object('ok',false,'error','unauthenticated'); end if; if _feedback not in ('useful','not_useful','dismiss','acted') then return jsonb_build_object('ok',false,'error','invalid_feedback'); end if; if not exists(select 1 from public.financial_situations where id=_situation_id and user_id=v_uid) then return jsonb_build_object('ok',false,'error','not_found'); end if; insert into public.financial_situation_feedback(user_id,situation_id,surface,feedback) values(v_uid,_situation_id,_surface,_feedback); insert into public.financial_situation_events(user_id,situation_id,event_type,narrative,metadata) values(v_uid,_situation_id,case when _feedback='acted' then 'acted' else 'feedback' end,case _feedback when 'acted' then 'Você abriu a ação recomendada.' when 'useful' then 'Você marcou esta leitura como útil.' else 'Você enviou feedback sobre esta leitura.' end,jsonb_build_object('feedback',_feedback,'surface',_surface)); return jsonb_build_object('ok',true); end $$;

update public.nino_diagnosis_config set contract_version='nino_diagnosis_contract.v1.1',assembler_version='v1_1',updated_at=now() where singleton;
revoke all on function public.nino_diag_select_action(text,text,jsonb,numeric) from public,anon,authenticated;
revoke all on function public.nino_diag_resolve_conflicts(uuid,text) from public,anon,authenticated;
revoke all on function public.nino_evaluate_future_situations(uuid,date,text,uuid) from public,anon,authenticated;
revoke all on function public.my_nino_situation_feedback(uuid,text,text) from public,anon;
grant execute on function public.my_nino_situation_feedback(uuid,text,text) to authenticated;
do $$ declare u record; begin for u in select id from auth.users loop perform public.nino_refresh_diagnosis(u.id,current_date,'live','v1_1_migration'); end loop; end $$;
commit;